### ISSUE TITLE
[FR] Publisher modal

### ISSUE THREAD

**Issue by andrey-jef** [ObsidianPublisher/obsidian-github-publisher#1]
Looks great. Thank Mara.

I would love to see how could you adopt the `Publication Center` feature from [oleeskild](https://github.com/oleeskild/obsidian-digital-garden) to make it easier to understand what files are published, which has changed, been deleted and are yet to be published.

![Screenshot 2022-04-12 182128](https://user-images.githubusercontent.com/81280428/163008700-984c09d1-a46a-4b15-8af8-7f8c0988042e.jpg)

Or if you two can collab. Since I dreamed of a [oleeskild](https://github.com/oleeskild/obsidian-digital-garden)'s published page with left navigation bar, top menu, right TOC pane like what you did with your mkdocs template :)

**Comment by andrey-jef** [comment]
aha. Thanks for explaining. At least for now, with the plugin, the workflow is already much better than using the obs2mk in terminal.

**Comment by Mara-Li** [comment]
Maybe in some time I will maybe code this, but it's not my priority !
I'm happy that this plugin help your worflow :D

**Comment by Mara-Li** [comment]
Okay, I tried to create the menu, but I really don't have the level for this ;_;
Maybe @oleeskild can give some hands/help on this ;_;

**Comment by oleeskild** [comment]
I'm sorry to say that I don't think I'll find the time in the near future, but I'll add it to my todolist to take a look at it if I find the time. 

If someone else is interested in implementing this, the code is available in my obsidian-digital-garden repo in the [PublishStatusManager.ts](https://github.com/oleeskild/obsidian-digital-garden/blob/main/src/PublishStatusManager.ts). 

In short what it does is using the GitHub API to retrieve the "tree" for the main branch. This contains the hashes for all files in your repo. Then I'm generating the hash locally for each file marked with a publish attribute in the frontmatter. Then I compare the two hashes. If they are equal the note is published. If they are unequal, the note is changed. If it's not present in the hashes from github it is unpublished. Lastly the deleted files are the ones that are present in the hashes from github, but not present in your vault. You are then left with 4 lists which you could render in a modal or similar.
