### ISSUE TITLE
[FR]: Use a different branch for publishing

### ISSUE THREAD

**Issue by sbusso** [ObsidianPublisher/obsidian-github-publisher#101]
### Issue validation

- [X] I checked the issue to prevent duplicate

### Is your feature related to a problem ?

I was looking to achieve a manual process similar to this plugin using a different branch to avoid getting templates and files mixed with obsidian notes. 

### What solution do you want to see ?

A `publish` branch would be rebased on `main` branch when calling the plugin action. The `publish` branch would have all the required elements to use the exported notes.

### OS

MacOS

### Plugin version

4.12

### Obsidian version & debug log

```shell
NA
```

**Comment by Lisandra-dev** [comment]
It exists already a way to use another branch. I don't understand why do you mean if it's not this option?

**Comment by sbusso** [comment]
I see the plugin can use a different main branch to work from or maybe I misunderstand it. What I would expect is for the main branch to remain untouched when publishing and for published notes to be in another branch.

**Comment by Lisandra-dev** [comment]
Maybe the name of the option is not pretty well written.

But yes, this option change the branch used by the plugin, so your main branch remains untouched.

**Comment by sbusso** [comment]
thanks for the reply. I will try it.
