### ISSUE TITLE
[Bug]: Clicking on "Deploy to Netlify" creates an empty GitHub repository

### ISSUE THREAD

**Issue by Jackiexiao** [ObsidianPublisher/obsidian-github-publisher#121]
### Describe the bug

click "Deploy to Netlify" in [document](https://obsidian-publisher.netlify.app/)  create an empty github repository, see: 

https://github.com/Jackiexiao/publisher-template-netlify

**Comment by Jackiexiao** [comment]
other issue

from: 
https://github.com/mfarragher/obsidiantools#%EF%B8%8F-installation
```
pip install obsidiantools
Requires Python 3.9 or higher.
```

I set python-version to 3.8 and netfliy build error, it seems we forget add `obsidiantools` to requirements, but it now require python 3.9
```
1:46:22 PM:   File "/opt/build/repo/overrides/hooks/on_env.py", line 16, in obsidian_graph
1:46:22 PM:     import obsidiantools.api as otools
1:46:22 PM: ModuleNotFoundError: No module named 'obsidiantools'
1:46:22 PM: ​
1:46:22 PM:   "build.command" failed                                        
1:46:22 PM: ────────────────────────────────────────────────────────────────
```

**Comment by Jackiexiao** [comment]
text placer not working

![image](https://user-images.githubusercontent.com/18050469/226821547-2cf582f0-2a17-475e-8716-8ee58e8ba79f.png)

but content like
```
%%hidecontent%%
```
still present in github repo (but not in netflify  website)， sometimes，we want hide content, where public github or netfliy website

**Comment by Lisandra-dev** [comment]
1. Please create discussion for this. 
2. Please create different discussion for different problem

---

1/ Definitively not normal
2/ Already the case, set .env file in `.github/` folder
3/ Check your regex with regex101 before making a issue.

**Comment by Jackiexiao** [comment]
get, I have create discussion for this

I see you disable graph view by default in netlify template: https://github.com/ObsidianPublisher/publisher-template-netlify/commit/29388f782c469fc5980903038f76b2cc7f14d157
