### ISSUE TITLE
[Bug]: TypeError: Cannot read properties of null (reading 'endsWith')

### ISSUE THREAD

**Issue by baksohyeon** [ObsidianPublisher/obsidian-github-publisher#132]
### Issue validation

- [X] I checked the issue to prevent duplicate
- [X] I checked my configurations files and the documentation

### Command used

Upload all notes, Upload unpublished notes, Upload single current active note
Refresh published and upload new notes, Refresh all published notes

### Plugin version

5.5.5

### Describe the bug

error log with **TypeError: Cannot read properties of null (reading 'endsWith')**

If the `Upload configuration > File tree in repository` configuration is `Obsidian path`, Error not occurred. 
But when I published new note using `YAML frontmatter` configuration with _Upload single current active note_ command, 
Making new branch and Uploading file to the repository are working
But merging progress that new branch is merged to the main branch what I configured is not implemented.

![image](https://user-images.githubusercontent.com/80398645/229337297-e1ccb8aa-4ab3-45f2-933d-3b7e8173d357.png)

Another issue is relavant. If refresh the notes (e.g. _Refresh published and upload new notes_ Command), cannot execute the function with this error log

```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'endsWith')
```

### How to reproduce ?

Publish notes with YAML format

### Minimal Reproducible Example

```
---
title: Hello
share: true
---
# Hello
asdf
```

→ I write the new note for the testing, but It is not working.

### Configuration

```json
{
  "github": {
    "branch": "main",
    "automaticallyMergePR": true,
    "api": {
      "tiersForApi": "Github Free/Pro/Team (default)"
    },
    "worflow": {
      "workflowName": "",
      "customCommitMsg": ""
    }
  },
  "upload": {
    "behavior": "yaml",
    "defaultName": "docs",
    "rootFolder": "docs",
    "yamlFolderKey": "category",
    "frontmatterTitle": {
      "enable": false,
      "key": "title"
    },
    "replaceTitle": [],
    "replacePath": [],
    "autoclean": {
      "enable": true,
      "excluded": [
        "docs/assets/js",
        "docs/assets/meta",
        "docs/assets/css",
        "docs/tags.md",
        "docs/assets/img"
      ]
    },
    "folderNote": {
      "enable": false,
      "rename": "index.md"
    },
    "metadataExtractorPath": ""
  },
  "conversion": {
    "hardbreak": true,
    "dataview": true,
    "censorText": [],
    "tags": {
      "inline": true,
      "exclude": [],
      "fields": []
    },
    "links": {
      "internal": true,
      "unshared": true,
      "wiki": true
    }
  },
  "embed": {
    "attachments": true,
    "keySendFile": [],
    "notes": true,
    "folder": "docs/attachments"
  },
  "plugin": {
    "shareKey": "share",
    "fileMenu": true,
    "editorMenu": false,
    "excludedFolder": [],
    "copyLink": {
      "enable": false
      "removePart": [
        ""
      ],
      "addCmd": false
    },
    "noticeError": false
  }
}
```

### Relevant log output

```shell
TypeError: Cannot read properties of null (reading 'endsWith')
    at Rl (plugin:obsidian-mkdocs-publisher:53:2714)
    at Al (plugin:obsidian-mkdocs-publisher:53:2936)
    at Ue (plugin:obsidian-mkdocs-publisher:53:4302)
    at sr.getAllFileWithPath (plugin:obsidian-mkdocs-publisher:57:7157)
    at eval (plugin:obsidian-mkdocs-publisher:54:35745)
    at Generator.next (<anonymous>)
    at s (plugin:obsidian-mkdocs-publisher:6:691)
```
![image](https://user-images.githubusercontent.com/80398645/229336968-90b4a270-657e-4c1d-940d-d7e6c10ba029.png)

- `Refresh published and upload new notes` Command error: 

![image](https://user-images.githubusercontent.com/80398645/229337345-9ee18ada-406c-49ed-ae0c-2ae3908077c5.png)

### OS

MacOS

### Anything else?

1. I've got into this problem when I updated obsidian github publisher plugin to version 5
2. For this issue, I've tried to using the this repository to using the latest version of template configuration that you recommended. →  https://github.com/ObsidianPublisher/follow_template 

### Obsidian information

```shell
SYSTEM INFO:
	Obsidian version: v1.1.16
	Installer version: v0.14.6
	Operating system: Darwin Kernel Version 22.3.0: Mon Jan 30 20:39:35 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T8103 22.3.0
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal
	Snippets enabled: 3
	Restricted mode: off
	Plugins installed: 25
	Plugins enabled: 25
		1: Obsidian Git v2.16.0
		2: Kanban v1.5.1
		3: Tweet to Markdown v2.12.1
		4: Advanced Tables v0.18.1
		5: Tag Wrangler v0.5.6
		6: Outliner v4.2.1
		7: Readwise Official v2.0.1
		8: Editor Syntax Highlight v0.1.3
		9: Emoji Shortcodes v2.2.0
		10: Copy as HTML v1.0.6
		11: Image Caption v0.0.13
		12: Find orphaned files and broken links v1.8.0
		13: Auto Link Title v1.4.1
		14: cMenu v1.1.2
		15: Dataview v0.5.54
		16: Templater v1.16.0
		17: Note Refactor v1.7.1
		18: Calendar v1.5.10
		19: Hotkeys for templates v1.4.3
		20: Checklist v2.2.12
		21: Simple Embeds v1.14.1
		22: Regex Find/Replace v1.2.0
		23: Linter v1.10.1
		24: Metacopy v1.9.1
		25: Github Publisher v5.5.5

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

**Comment by Lisandra-dev** [comment]
Could you try with a custom commit message?

Normally, there is a default message but maybe it's buggy so...

**Comment by baksohyeon** [comment]
I think still not working though T.T 


```
// data.json (plugin settings)
{
  "github": {
    "branch": "main",
    "automaticallyMergePR": true,
    "api": {
      "tiersForApi": "Github Free/Pro/Team (default)"
    },
// here 
    "worflow": {
      "workflowName": "auto_update.yml", // The same result even if delete it
      "customCommitMsg": "[Merge]" // custom commit message
    }
  },
 ...
}
```

**Comment by Lisandra-dev** [comment]
The Workflow here is not relevant! You don't need it.

**Comment by baksohyeon** [comment]
Can I ask you to explain in more detail what I have to do?

**Comment by Lisandra-dev** [comment]
I try to understand why it's doesn't work, please wait.

**Comment by Lisandra-dev** [comment]
Can't repro :(
1. Could you try to delete the old branch ?
2. Could you try to reload Obsidian ?

**Comment by baksohyeon** [comment]
1, 2  → It did not affect the outcome.
3. → Where can I get the new beta version?

**Comment by baksohyeon** [comment]
Oh, It just came to my mind, I'll delete and reinstall the plugin.

**Comment by Lisandra-dev** [comment]
> 1, 2 → It did not affect the outcome. 3. → Where can I get the new beta version?

Latest release

**Comment by baksohyeon** [comment]
Yeah, I've try with latest version of plugin and template,
I think... reinstalling the plug-in seems to have solved it. 


It's been a problem I've been experiencing for two weeks, but I don't know why it happened, but I deleted it and reinstalled it, so it works fine.

In my opinion, I received the modified main source code of the plug-in separately from you at the discord, and I think that might be the effect.

**Comment by baksohyeon** [comment]
I'm embarrassed that it's been solved unexpectedly, haha I think it's a problem on my end. Thank you very much for your quick response!

**Comment by Lisandra-dev** [comment]
I really don't know why it does that, so I live the issue open in case someone have the same problem!

**Comment by baksohyeon** [comment]
Umm, I think I checked the result incorrectly. The same error occurs.

**Comment by Lisandra-dev** [comment]
I really can't success to reproduce the error :s 
Could you please try to use the last beta ? Just download it from release and replace the main.js in `.obsidian/plugin/obsidian-mkdocs-publisher` ?

**Comment by baksohyeon** [comment]
still not working,,

**Comment by Lisandra-dev** [comment]
Did you try with another repository, by any chance ?

**Comment by baksohyeon** [comment]
Things I've done:
1. Keep plugin, templates up-to-to-date
2. Uninstalling and reinstalling the plug-in will not solve the problem
3. Manual replacement of main.js
4. Deleting custom css 
→ still not working.

---
I've tried on the single-current note, but same issue
![image](https://user-images.githubusercontent.com/80398645/229345162-843e6e33-6ef4-4bb7-83d0-c90302093c79.png)


OK, Let me check what I should I do

1. debug mode on original repository
2. create new repository and then try to publish
3. if error continues on the new repo, then debug mode

Can you check it out?

**Comment by baksohyeon** [comment]
![image](https://user-images.githubusercontent.com/80398645/229346035-63f7dadf-759c-4428-9ec7-dfebd4a3a079.png)

![image](https://user-images.githubusercontent.com/80398645/229346127-f7655c96-bca6-4b39-858f-e7e5d3366a1f.png)


I hope it's helpful information.

**Comment by Lisandra-dev** [comment]
It's perfect! Thanks ✨
