### ISSUE TITLE
[Plugin][FR]: Publish to Local Directory

### ISSUE THREAD

**Issue by PatrickAmbrosso** [ObsidianPublisher/obsidian-github-publisher#148]
### Issue validation

- [X] I checked the issue to prevent duplicate

### Is your feature related to a problem ?

I know the name of the plugin is Obsidian "GitHub" Publisher, but it would be great to have an option to export it locally to a directory. I plan on hosting via other platforms, for which I need to process the notes before uploading. Which I plan to do via Windows PowerShell. 

The plugin already does the majority of work of formatting the notes. So, if the plugin could have an option to export to a local directory, it would be fantastic!

### What solution do you want to see ?

An option to export to local directory. 

### Describe the alternative you've considered

NA

### OS

Windows, Linux

### Anything else?

NA

### Plugin version

5.7.0

### Obsidian version & debug log

```bash session
SYSTEM INFO:
	Obsidian version: v1.2.8
	Installer version: v1.1.9
	Operating system: Windows 10 Home Single Language 10.0.22621
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: AnuPpuccin v1.4.2
	Snippets enabled: 9
	Restricted mode: off
	Plugins installed: 27
	Plugins enabled: 26
		1: Tag Wrangler v0.5.8
		2: Templater v1.16.0
		3: QuickAdd v0.23.0
		4: Advanced Tables v0.18.1
		5: Frontmatter Tag Suggest v0.4.1
		6: Natural Language Dates v0.6.1
		7: Periodic Notes v0.0.17
		8: Dataview v0.5.55
		9: Supercharged Links v0.9.6
		10: Calendar v1.5.10
		11: Editor Syntax Highlight v0.1.3
		12: Style Settings v1.0.3
		13: Excel to Markdown Table v0.4.0
		14: Bible Reference v1.6.0
		15: Outliner v4.6.7
		16: Book Search v0.5.10
		17: Media DB Plugin v0.5.1
		18: Minimal Theme Settings v6.3.1
		19: Recent Files v1.3.5
		20: Paste image rename v1.6.1
		21: Github Publisher v5.7.0
		22: ePub Reader v1.0.2
		23: Quiet Outline v0.3.15
		24: Obsidian Git v2.19.1
		25: Excalidraw v1.9.0
		26: Obsidian markdown export v1.0.8

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

**Comment by Lisandra-dev** [comment]
As I said multiple time : it's too much complicated to allowing local folder. 

It's will be a total rewrite of the plugin and I don't have the time nor the envy to do it.
