### ISSUE TITLE
[FR]: support vuepress to generate website

### ISSUE THREAD

**Issue by windily-cloud** [ObsidianPublisher/obsidian-github-publisher#15]
### Issue validation

- [X] My issue is not a question relative to [Material Mkdocs](https://squidfunk.github.io/mkdocs-material/) nor [Mkdocs](https://www.mkdocs.org/) (*[You can open a discussion to get more help!](https://github.com/squidfunk/mkdocs-material/discussions)*)
- [X] I checked the issue to prevent duplicate

### Workflow

Obsidian plugin 💠

### What solution do you want to see ?

I imagine the publishing plugin for obsidian is very similar to what you're doing now, but mkdoc doesn't look very prerfect.

So I think using vuepress as a static blog generator would be a better choice because:

1. theoretically support all features of mkdoc, and now except folder note and hover preview are supported
2. besides, obsidian chart plugin, obsidian echart plugin, even advanced slide etc. are also supported, but the syntax is different.
3. most importantly, there is a lot of optimization for blogs, such as seo, article list , timeline, rss and so on

You can check [vuepress theme hope](https://vuepress-theme-hope.github.io/v2/guide/markdown/include.html) to get all features.

In order to adapt obsidian syntax in vuepress, I am going to write a vuepress plugin —— [vuepress-plugin-obsidian](https://github.com/windily-cloud/vuepress-plugin-obsidian). The general framework is ready and is expected to be completed in the next few weeks

My general idea is as follows:

![image](https://user-images.githubusercontent.com/30640638/178495069-2ebbb51f-4ee8-4512-81d2-ec86ce50a42e.png)

I would appreciate it if you could do an adaptation of vuepress, depending on your idea of how to do it. 

Finally, I can translate this obsidian plugin into Chinese(Currently the plugin does not have i18n, I can also add if you do not mind).

Thanks for any reply!!!

### OS

Windows

**Comment by Mara-Li** [comment]
Hello ! 
First, I will love to saw a translation of the plugin in different language, as I search how i can do it.

About vuepress... Well, JS-TS is not my primary langage. I choosen mkdocs because i know python so i can write some plugin to add some feature i wanted. Vuepress seems pretty cool, so if you want to create your template, you can ! I will update the doc to add it.

Github Publisher can add any obsidian markdown file to any repo, so the plugin is "template agnostic".

I don't think i will wrote a New template for the moment but i will love to saw a vuepress version !

**Comment by Mara-Li** [comment]
If you want the same tree/hierarchy in github and obsidian, you can use the "Obsidian path" option!

**Comment by windily-cloud** [comment]
> If you want the same tree/hierarchy in github and obsidian, you can use the "Obsidian path" option!

Wow, that's wonderful.

At the same time, I would like to make a settings page dedicated to vuepress. Do you allow PR?

**Comment by Mara-Li** [comment]
Obviously! Go ahead here : https://github.com/obsidianMkdocs/obsidian_mkdocs_publisher_docs to make a settings page dedicated !
If you need, you can create a new folder or simply a page for github publisher with updating the configuration example page!

**Comment by windily-cloud** [comment]
Since I needed to add a lot of features to the plugin and I was not familiar with web programming, I pulled a partner. He suggested that I recreate a plugin that would improve development efficiency as well as greater freedom, and I will therefore support vuepress on the new plugin.

I'm sorry we couldn't work together!

**Comment by Mara-Li** [comment]
oh :( Sad! I hope saw your plugin in the future! 
Also, please, bump me when you publish your vuepress plugin, as I can saw if I can add compatibility with it :).

**Comment by windily-cloud** [comment]
I mainly based on two points of consideration.

1. China's network environment is special, some people can't login to github (it doesn't affect me much), many people will build blogs on gitee
2. the existence of vuepress and mkdoc at the same time will bother new users. Too many settings and too many commands are problems.All my settings are deeply bound to vuepress.

I'll share the plugin with you when I'm done, Thank you and have a nice day!😆😆😆
