### ISSUE TITLE
[Bug]: HTML-Links to folder note files do not work

### ISSUE THREAD

**Issue by emign** [ObsidianPublisher/obsidian-github-publisher#17]
### Issue validation

- [X] My issue is not a question relative to [Material Mkdocs](https://squidfunk.github.io/mkdocs-material/) nor [Mkdocs](https://www.mkdocs.org/) (*[You can open a discussion to get more help!](https://github.com/squidfunk/mkdocs-material/discussions)*)
- [X] I checked the issue to prevent duplicate
- [X] I checked my configurations files and the documentation

### Workflow

Obsidian plugin 💠

### Describe the bug

Hallo,

I really love your plugin. I use `obs2mk` in a docker container to convert my obsidian markdown file-structure to an mkdoc page. I use this line in a bash script:
```
find /docs -type f -name \*.md -exec bash -c 'FN="{}"; obs2mk --minimal file "{}"' \;
```
I have the following folder structure:
![image](https://user-images.githubusercontent.com/5278352/181845450-256363c9-6610-45f8-a1c3-cf786ec4bca2.png)
**note that the icons are from the folder-icons plugin and do not belong to the filenames**

Please checkout the resulting mkdocs file here: [https://unterricht.emig.me/Unterricht/Fächer/Biologie/NuT/Ökosystem%20Grünland/](https://unterricht.emig.me/Unterricht/Fächer/Biologie/NuT/Ökosystem%20Grünland/)

The links to the folder-note files do not work. They are not correctly linked.
For example the link to "Stoffwechsel" points to `../../../../Stoffwechsel` instead of `../Der%20%Mensch%20als%20Lebewesen/Stoffwechsel`
Please note, that the link in the navigation bar on the left is correctly created

### How to reproduce ?

1. In Obsidian: Create a folder and inside that a MD file with the same name as the folder (folder-note)
2. Link to the folder note markdown file from an external markdown file
3. Convert files using obs2mk

### Configuration

using `--minimal` argument it should use your minimal config:
```
minimal:
  configuration:
    input: null
    output: null
  frontmatter:
    category:
      default value: notes
      key: category
    index: (i)
    share: share
  weblink: null
```

### OS

Linux

**Comment by Mara-Li** [comment]
Huuuuuuuuuuh
Did you try without using the old python plugin ? 
I saw (on my own file) that sometimes, python broke completely the filepath.

**Comment by emign** [comment]
What do you mean by 'without using the old python plugin?' ?
is `osb2mk` not maintained anymore? 
The problem I have with using the obsidian plugin is, that I have to use a git repo which is hosted on my own server instead of GitHub

**Comment by Mara-Li** [comment]
As I said in the documentation, obs2mk is deprecated. I prefer to maintain the obsidian plugin.

You can totally maintain obs2mk if you want !

More over, I think i will work on a way to use a local folder and other Git solution (at last Gitlab and Gitea).

**Comment by emign** [comment]
Sorry I did not see that in the documentation. 
I am considering contributing to obs2mk

And it would be really awesome if you would integrate local folder or general git support (not only gitlab etc)

**Comment by Mara-Li** [comment]
The problem around local is simple : i dont want to broke mobile. So i need to found a way to disable this option on mobile !
I think i will work on that this summer :)

**Comment by Mara-Li** [comment]
Hello ! I started to work on local folder, but it's a highly destructive behavior, with a lot of work for a niche usage (at my side).
If you want to help me, you can check the branch "local_folder" and help me to test and try !
