### ISSUE TITLE
[Plugin][Bug]: Backslash for regex patterns rejection

### ISSUE THREAD

**Issue by quinn-p-mchugh** [ObsidianPublisher/obsidian-github-publisher#172]
### Issue validation

- [X] I checked the issue to prevent duplicate
- [X] I checked my configurations files and the documentation

### Plugin version

6.2.2

### Describe the bug

In the "Folder path & filename replacer" screen, using backslashes in the regex expression causes an error.

![Folder path & filename replacer](https://github.com/ObsidianPublisher/obsidian-github-publisher/assets/40648753/0b6c752b-8878-457b-8f91-4534fa1f2741)

I'm trying to replace all whitespace with dashes, but it seems this is not possible if I can't use `\s` in the regex expression.

### How to reproduce ?

1. Got to plugin settings
2. Click the **Upload configuration** tab
3. Edit "Apply edit on the folder path or the filename (automatically)"
4. Enter `/\s+/` as the "Value to replace"
5. Click **Save**
6. Error on top right: "File name cannot contain character: \"

Trying to escape the backslash using `//\s+/` or `/\\s+/` yields the same output.

### Minimal Reproducible Example

N/A

### Configuration

```JSON
{
  "github": {
    "branch": "main",
    "automaticallyMergePR": true,
    "tokenPath": "%configDir%/plugins/%pluginID%/env",
    "api": {
      "tiersForApi": "Github Free/Pro/Team (default)",
      "hostname": ""
    },
    "workflow": {
      "commitMessage": "[Obsidian GitHub Publisher] Merge",
      "name": ""
    }
  },
  "upload": {
    "behavior": "yaml",
    "defaultName": "docs",
    "rootFolder": "",
    "yamlFolderKey": "publish-path",
    "frontmatterTitle": {
      "enable": true,
      "key": "publish-title"
    },
    "replaceTitle": [
      {
        "regex": "",
        "replacement": "",
        "type": "title"
      }
    ],
    "replacePath": [],
    "autoclean": {
      "enable": false,
      "excluded": []
    },
    "folderNote": {
      "enable": false,
      "rename": "index.md"
    },
    "metadataExtractorPath": ""
  },
  "conversion": {
    "hardbreak": false,
    "dataview": true,
    "censorText": [],
    "tags": {
      "inline": false,
      "exclude": [],
      "fields": []
    },
    "links": {
      "internal": false,
      "unshared": false,
      "wiki": false,
      "slugify": false
    }
  },
  "embed": {
    "attachments": true,
    "keySendFile": [],
    "notes": false,
    "folder": ""
  }
}
```

### OS

Windows

### Anything else?

I'm aware regex expressions need to be enclosed in forward slashes (`/`), per [this page](https://obsidian-publisher.netlify.app/plugin/settings/upload/?h=regex#regex-on-filename-folder-path:~:text=order%20of%20registration.-,To%20use%20the%20regex%2C%20you%20need%20to%20enclose%20the%20text%20with,.,-About%20folder%20Path).

### Obsidian information

```bash session
SYSTEM INFO:
	Obsidian version: v1.3.5
	Installer version: v1.3.5
	Operating system: Windows 10 Pro 10.0.22621
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: none
	Snippets enabled: 6
	Restricted mode: off
	Plugins installed: 102
	Plugins enabled: 15
		1: Readwise Official v2.0.1
		2: Dataview v0.5.56
		3: Templater v1.16.0
		4: Linter v1.14.0
		5: Text to Speech v0.5.1
		6: Projects v1.16.0
		7: Excalidraw v1.9.3
		8: Obsidian42 - Strange New Worlds (SNW) v1.2.2
		9: Pieces for Developers v0.3.11
		10: Recent Files v1.3.5
		11: Obsidian Better Internal Link Inserter v1.0.0
		12: Juggl v1.4.0
		13: Task Collector (TC) v1.0.11
		14: Markdown Blogger v1.0.0
		15: Github Publisher v6.2.2

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

**Comment by Lisandra-dev** [comment]
Thanks for the report! I totally forgot the backslash for regex.

**Comment by quinn-p-mchugh** [comment]
@Lisandra-dev 
Wow - thank you for the extremely prompt reply!

Looking forward to testing this soon. Have a great weekend!
