### ISSUE TITLE
[Plugin][FR]: Remove .md extension from generated links

### ISSUE THREAD

**Issue by quinn-p-mchugh** [ObsidianPublisher/obsidian-github-publisher#176]
### Issue validation

- [X] I checked the issue to prevent duplicate

### Is your feature related to a problem ?

I recently confirmed that [Docusaurus does not support relative markdown linking between blog and doc pages](https://github.com/facebook/docusaurus/issues/9117).

This means that the relative markdown links (`[link](../../docs/.md#)` ) generated by the Obsidian GitHub Publisher plugin do not work for links between pages in the `blog` section and the `docs` section any Docusaurus website. This might be fixed in the future, but [one of the lead developer's notes that this would require a significant change to how links are routed in Docusaurus](https://github.com/facebook/docusaurus/issues/9117#:~:text=I%27d%20like%20to%20support%20cross%2Dplugin%20relative%20links%20but%20it%20would%20require%20the%20core%20engine%20to%20somehow%20maintain%20a%20%22file%20path%20%2D%3E%20URL%20path%22%20mapping%2C%20and%20we%20probably%20need%20additional%20plugin%20lifecycle%20hooks%20for%20that.).

However, using **standard** URL links (without the `.md` extension) work just fine.

**For example:**
If I provide a link in a blog post like `[link](../../docs/relevant-doc-page.md#)`, the link does _not_ work.

whereas...

When I remove the `.md` extension (`[link](../../docs/relevant-doc-page)`), the link routes successfully.

### What solution do you want to see ?

As a workaround, I'd like an option to remove the `.md` extension from all wikilinks that are converted to relative markdown links, so these links work properly on websites built with Docusaurus.

So instead of: `[link](../../docs/relative-doc-page.md#)`

It should be: `[link](../../docs/relative-doc-page)`

This could be a matter of including the file extension in any user-specified regular expressions in the `Apply edit on the folder path or filename (automatically)` setting, allowing users to remove the `.md` file extension by specifying `.md` under `Value to replace` and nothing for the `Replacement` value.

### Describe the alternative you've considered

Other solutions might look like:
- Providing a boolean option (i.e. `Omit .md file extension?`) in the `Content's conversion` section to omit the `.md` file extension for any `[[Wikilinks]]` that are converted to `[MDlinks](links)`.

### OS

Windows

### Anything else?

I think enabling the ability to modify file extensions (in addition to filename and folder path) in the `Apply edit on the folder path or filename (automatically)` setting would be the most flexible solution. However, this may or may not cause issues in the event that users' existing regex replace settings happen to match the `.md` file extension.

### Plugin version

6.2.5

### Obsidian version & debug log

```bash session
N/A
```

**Comment by Lisandra-dev** [comment]
Real question: did you try to use the regex replacement of contents to remove the .MD extension?

**Comment by quinn-p-mchugh** [comment]
Hi @Lisandra-dev,

Good question - this may very well be a case of user error!

I'll give the above suggestion a try, but given that using backslashes yield an error (see #172), I'll need to wait until the new release to try it out.

Thanks for your prompt response! Very much appreciate the help here.

**Comment by quinn-p-mchugh** [comment]
FWIW, I've confirmed that the following (non-regex) replacement does not remove the `.md` extension.

![image](https://github.com/ObsidianPublisher/obsidian-github-publisher/assets/40648753/4fc39054-8664-4fef-8079-844e03e142cd)

**Comment by Lisandra-dev** [comment]
As I said in my first post, you need to set the regex in the content remplacement. Not in the path remplacement.

**Comment by quinn-p-mchugh** [comment]
Hi @Lisandra-dev,

Ah, thank you - I'll read more carefully next time.

It seems the following settings in the `Text replacer` setting due not modify markdown links in any way.

**Comment by quinn-p-mchugh** [comment]
Hi @Lisandra-dev,

Ah, thank you - I'll read more carefully next time.

Hmmm... it seems the following settings in the `Text replacer` setting due not modify markdown links.
![image](https://github.com/ObsidianPublisher/obsidian-github-publisher/assets/40648753/ea1fa773-fb12-4c7e-920e-6f601b114acb)

The [`convertWikiLinks function is called before the `findAndReplaceText` function](https://github.com/ObsidianPublisher/obsidian-github-publisher/blob/1d2c883507996d27f8f5a8cf46d0b1043b213c46/src/conversion/convert_text.ts#L367-L368).

# Test file contents (In Obsidian):

## test-blog-post.md
```
---
publish: true
publish-path: blog/2022
publish-filename: 
---
[[test-docs-post]]
```

## test-docs-post.md
```
---
publish: true
publish-path: docs
publish-filename: 
---
[[test-blog-post]]
```

# Result (In GitHub)

## test-blog-post.md
```
---
publish: true
publish-path: blog/2022
publish-filename: 
---
[test-docs-post](../../docs/test-docs-post.md#)
```

## test-docs-post.md
```
---
publish: true
publish-path: docs
publish-filename: 
---
[test-blog-post](../blog/2022/test-blog-post.md#)
```

I might have to do some debugging on my end

**Comment by Lisandra-dev** [comment]
Change the arrow to down :)

**Comment by quinn-p-mchugh** [comment]
Ah, shoot. Thank you @Lisandra-dev! Changing the arrow to down resolved my issue. 

I've provided the full resolution below for anyone with similar inquiries.

# Solution (to remove `.md` from markdown links)
- Go to **Content's conversion** section.
- Edit **Text replacer** setting.
- Add a new entry using the plus button.
- Enter the following regex `/(\[.*?\]\(.*?).md(.*?\))/` under **Value to Replace** 
- Under **Replacement**, enter `$1$2`.
- Click the arrow and make sure it is pointed **downward**.
- Click **Save**
- Reload plugin, if necessary.

**Comment by Lisandra-dev** [comment]
What do you mean by the links in dataview ?

**Comment by abbychau** [comment]
Tables in dataview have a link called `File`, which is a link.

**Comment by Lisandra-dev** [comment]
![image](https://github.com/ObsidianPublisher/obsidian-github-publisher/assets/30244939/31a1c974-6c27-4b07-b829-8713a5e92cf6)
No problem on my side :/

**Comment by abbychau** [comment]
mine is this:
```
  "conversion": {
    "hardbreak": true,
    "dataview": true,
    "censorText": [
      {
        "entry": "/(\\[.*?\\]\\(.*?).md(.*?\\))/",
        "replace": "$1$2",
        "flags": "",
        "after": true
      }
    ],
    "tags": {
      "inline": false,
      "exclude": [],
      "fields": []
    },
    "links": {
      "internal": true,
      "unshared": false,
      "wiki": true,
      "slugify": true
    }
  },
```

in your screenshot, it seems that only the first row of the table was replaced but other links are still with `.md` is that right?

**Comment by Lisandra-dev** [comment]
Oh, yeah, I think you need to use `g` in the regex

**Comment by abbychau** [comment]
I have added g at the end. but no matter if it is added or unadded. .md is still not being replaced.

**Comment by Lisandra-dev** [comment]
![image](https://github.com/ObsidianPublisher/obsidian-github-publisher/assets/30244939/e60b29d0-8264-4914-abd1-bfc2272c3369)
Works on my side :/

**Comment by abbychau** [comment]
I rebuilt my repo and it is working now. thanks.
(the plugin was not pushing changes after editing at all.
