### ISSUE TITLE
[Plugin][Bug]: Can't select regex flags like gi

### ISSUE THREAD

**Issue by mathisgauthey** [ObsidianPublisher/obsidian-github-publisher#180]
### Issue validation

- [X] I checked the issue to prevent duplicate
- [X] I checked my configurations files and the documentation

### Command used

Upload single current active note

### Plugin version

6.3.1

### Describe the bug

Can't select the regex key `gi` for global incensitive.
The issue is that my regex only applies to the first link it founds, hence all my internal links for attachments and other notes are not converted.

![image](https://github.com/ObsidianPublisher/obsidian-github-publisher/assets/46576952/92a9555c-9079-4219-b4b9-b667bea5b425)

### How to reproduce ?

Go into setting try applying the text conversions here :

Images :

`/!\[\[([^[\]]+)\]\]/` -> `![$1](/images/$1)`

Post links :

`/\[\[([^\]]+)\]\]/` -> `[$1]({{< ref "$1" >}})`

Check regex : [regex101: build, test, and debug regex](https://regex101.com)

Original discussion : [How can I add a timestamp before the note title to upload ? · ObsidianPublisher · Discussion #179 · GitHub](https://github.com/orgs/ObsidianPublisher/discussions/179)

### Minimal Reproducible Example

I mean, the first link only is converted, it seems to be because of the flag applied to the regex search feature.

### Configuration

```JSON
{
  "github": {
    "branch": "main",
    "automaticallyMergePR": true,
    "api": {
      "tiersForApi": "Github Free/Pro/Team (default)",
      "hostname": ""
    },
    "workflow": {
      "name": "",
      "commitMessage": "[PUBLISHER] MERGE"
    },
    "tokenPath": ".obsidian/plugins/obsidian-mkdocs-publisher/env",
    "verifiedRepo": true
  },
  "upload": {
    "behavior": "fixed",
    "subFolder": "",
    "defaultName": "content/post",
    "rootFolder": "",
    "yamlFolderKey": "",
    "frontmatterTitle": {
      "enable": true,
      "key": "title"
    },
    "replaceTitle": [],
    "autoclean": {
      "enable": false,
      "excluded": [
        "docs/assets/js",
        "docs/assets/meta",
        "docs/assets/css",
        "tags.md",
        "graph.md"
      ]
    },
    "folderNote": {
      "enable": true,
      "rename": "index.md"
    },
    "metadataExtractorPath": "",
    "replacePath": []
  },
  "conversion": {
    "hardbreak": false,
    "dataview": false,
    "censorText": [
      {
        "entry": "/!\\[\\[([^[\\]]+)\\]\\]/",
        "replace": "![$1](/images/$1)",
        "after": false
      },
      {
        "entry": "/\\[\\[([^\\]]+)\\]\\]/",
        "replace": "[$1]({{< ref \"$1\" >}})",
        "after": false
      }
    ],
    "tags": {
      "inline": false,
      "exclude": [],
      "fields": []
    },
    "links": {
      "internal": false,
      "unshared": false,
      "wiki": false
    }
  },
  "embed": {
    "attachments": true,
    "keySendFile": [],
    "notes": true,
    "folder": "content/images"
  }
}
```

### OS

Windows, Linux

### Anything else?

Yes, it should be on the settings as seen in this [discussion](https://github.com/orgs/ObsidianPublisher/discussions/51).

![image](https://github.com/ObsidianPublisher/obsidian-github-publisher/assets/46576952/ae39f140-5d3c-4c1d-9285-6f98b10dd646)

Check regex : [regex101: build, test, and debug regex](https://regex101.com)

Original discussion : [How can I add a timestamp before the note title to upload ? · ObsidianPublisher · Discussion #179 · GitHub](https://github.com/orgs/ObsidianPublisher/discussions/179)

### Obsidian information

```bash session
SYSTEM INFO:
	Obsidian version: v1.3.5
	Installer version: v1.1.9
	Operating system: Windows 10 Pro 10.0.22621
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: adapt to system
	Community theme: AnuPpuccin v1.4.2
	Snippets enabled: 2
	Restricted mode: off
	Plugins installed: 35
	Plugins enabled: 33
		1: Calendar v1.5.10
		2: Better Word Count v0.9.6
		3: Auto Link Title v1.4.1
		4: Clear Unused Images v1.1.0
		5: Code Editor Shortcuts v1.14.0
		6: Colorful Tag v1.3.2
		7: Dataview v0.5.56
		8: File Explorer Note Count v1.2.1
		9: Filename Heading Sync v1.9.0
		10: Find orphaned files and broken links v1.9.0
		11: Footnote Shortcut v0.1.2
		12: Frontmatter Tag Suggest v0.4.1
		13: Icon Folder v2.1.2
		14: Kanban v1.5.3
		15: Linter v1.16.0
		16: Note Refactor v1.7.1
		17: Paste image rename v1.6.1
		18: Paste URL into selection v1.7.0
		19: Periodic Notes v0.0.17
		20: Style Settings v1.0.6
		21: Symbols Prettifier v1.1.1
		22: Tag Wrangler v0.5.11
		23: Tasks v4.1.0
		24: Templater v1.16.0
		25: Todoist Plugin v1.11.1
		26: Omnivore v1.5.3
		27: Better footnote v1.0.1
		28: Editing Toolbar v2.3.1
		29: Image Toolkit v1.3.1
		30: Quick Explorer v0.2.8
		31: Show Whitespace v0.3.1
		32: Google Calendar v1.9.19
		33: Github Publisher v6.3.1

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

**Comment by Lisandra-dev** [comment]
You need to write `/!\[\[([^[\]]+)\]\]/gi`

**Comment by mathisgauthey** [comment]
Only the two first link get changed with my initial post setup :
```
Create an Obsidian profile :

![2023-03-09_13-42-12_Tasker_Obsidian_profile.png](/images/2023-03-09_13-42-12_Tasker_Obsidian_profile.png)

Setup the following task :

![2023-03-09_13-42-12_Tasker_Termux_backup.png]({{< ref "2023-03-09_13-42-12_Tasker_Termux_backup.png" >}})

![[2023-03-09_13-42-12_Tasker_Termux_backup_task.png]]

![[2023-03-09_13-42-12_Tasker_Termux_stdout.png]]

![[2023-03-09_13-42-12_Tasker_Termux_stderr.png]]
```

If I try to manually add `gi`, nothing is converted at all.

**Comment by Lisandra-dev** [comment]
Pretty strange

Can I have the original output and the "expected" output ? I will check with debug mode (aka dev + console.log() xD)

**Comment by mathisgauthey** [comment]
Sure, here's a [link](https://regex101.com/r/ItBDSs/1).

Input : 

```
Create an Obsidian profile :

![[2023-03-09_13-42-12_Tasker_Obsidian_profile.png]]

Setup the following task :

![[2023-03-09_13-42-12_Tasker_Termux_backup.png]]

![[2023-03-09_13-42-12_Tasker_Termux_backup_task.png]]

![[2023-03-09_13-42-12_Tasker_Termux_stdout.png]]

![[2023-03-09_13-42-12_Tasker_Termux_stderr.png]]
```

Output : 

```
Create an Obsidian profile :

![2023-03-09_13-42-12_Tasker_Obsidian_profile.png](/images/2023-03-09_13-42-12_Tasker_Obsidian_profile.png)

Setup the following task :

![2023-03-09_13-42-12_Tasker_Termux_backup.png](/images/2023-03-09_13-42-12_Tasker_Termux_backup.png)

![2023-03-09_13-42-12_Tasker_Termux_backup_task.png](/images/2023-03-09_13-42-12_Tasker_Termux_backup_task.png)

![2023-03-09_13-42-12_Tasker_Termux_stdout.png](/images/2023-03-09_13-42-12_Tasker_Termux_stdout.png)

![2023-03-09_13-42-12_Tasker_Termux_stderr.png](/images/2023-03-09_13-42-12_Tasker_Termux_stderr.png)
```

**Comment by Lisandra-dev** [comment]
Thanks!

**Comment by Lisandra-dev** [comment]
My setup :

![image](https://github.com/ObsidianPublisher/obsidian-github-publisher/assets/30244939/ef62aade-7325-4cb1-b499-f297811dfa64)

Output :

![image](https://github.com/ObsidianPublisher/obsidian-github-publisher/assets/30244939/c6bc369f-afff-4e2c-bf74-e97852098e64)

It seems the two regex “collide.
Deleting one of the regex:
![image](https://github.com/ObsidianPublisher/obsidian-github-publisher/assets/30244939/727b9c1c-7a10-4e73-bbc5-52e04ae27e81)

Update : Fill too much stupid and forgot to parse the flags when I updated how regex was parsed…

**Comment by mathisgauthey** [comment]
I don't get it, did you manage to make it work ? Or does it need an update of the plugin ?

**Comment by Lisandra-dev** [comment]
I need to update some things to fix it!

**Comment by Lisandra-dev** [comment]
The issue was caused because I reworked how the regex was registered, and forgot to update the regex detection (it doesn't detect the flags nor the regex if you use any flags).
It is now fixed, see output below :

![image](https://github.com/ObsidianPublisher/obsidian-github-publisher/assets/30244939/52a1e975-10dd-4682-855d-d003c8e0fa07)

Btw, the two regex collide, as I said before, so you need to update it to strictly exclude the image from the second regex. 
Or, you could "invert" the two regex. Maybe the second option will work.

**Comment by mathisgauthey** [comment]
Alright first of all thanks for being such a reactive dev and for the update, it's really impressive.

Secondly concerning the two regex colliding, I used the two regex in this particular order because if the regex used attachment is first, it will change all `![[]]` links, and then the remaining `[[]]` can get fixed by the second regex.

This implies that I don't have embedded notes, but this would be a pain to manage for the auto-upload to my website, and I don't use embedded note this much, just wikilinks everywhere.

I don't really understand how they would still be colliding with the right order, but when I get back on my laptop I'll check your solution.

**Comment by mathisgauthey** [comment]
Alright I tested my solution, with the regex in the right order it does work.

Your solution works too, but it's more code or reversing the regex if I understood correctly, hence I'll take the easy path.

Althought, I think it would be great to include an example in the text replacer settings, something along the line of :

> Replace text in the file with the given value. If using regex, enclose the input with `/` and add a flag outside if reguired. Use basic regex for the ouput. Example : `/\[\[([^\]]+)\]\]/gi` -> `[$1]({{< ref "$1" >}})`

And I guess the docs could use of something like that, and stating that the position of the replace text is important. Maybe a way to re-organise in the plugin UI them could be great in the future.

I'll be glad to help with the plugin when I get some internet connection, but I might only be usefull for the documentation with my current knowledge.
