### ISSUE TITLE
[Bug]: Wikilink to Markdown link conversion has trailing "]" in filename

### ISSUE THREAD

**Issue by Vuenc** [ObsidianPublisher/obsidian-github-publisher#19]
### Issue validation

- [X] My issue is not a question relative to [Material Mkdocs](https://squidfunk.github.io/mkdocs-material/) nor [Mkdocs](https://www.mkdocs.org/) (*[You can open a discussion to get more help!](https://github.com/squidfunk/mkdocs-material/discussions)*)
- [X] I checked the issue to prevent duplicate
- [X] I checked my configurations files and the documentation

### Workflow

Obsidian plugin 💠

### Describe the bug

I noticed the following bug for an image link that was converted to a markdown link: the link should have been "myfile.png", but was "myfile.png%5D", where the %5D is percent encoding for the "]" character.

I believe this bug comes from the `convertWikilinks()` method in `convertText.ts`: The `fileRegex` captures "[[", "|" and "]". A few lines later, "[[" and "|" are replaced by "", but "]" is not replaced.

Best and thanks for the useful plugin!

### How to reproduce ?

Create a markdown file which references an image myfile.png via a link ![[myfile.png]].

Push the file to github.

Check if the image link has a trailing "%5D" which prevents it from working.

### Configuration

-

### OS

Linux

**Comment by Mara-Li** [comment]
Good catch ! I will fix that asap :)
