### ISSUE TITLE
[Plugin][FR]: Add custom README.md 

### ISSUE THREAD

**Issue by tsievert** [ObsidianPublisher/obsidian-github-publisher#197]
### Issue validation

- [X] I checked the issue to prevent duplicate

### Is your feature related to a problem ?

I'm publishing to a private repository, so the first thing you see properly rendered would be `README.md`. 
However, I don't want to have a `README.md` in my every day Obsidian use, because I only need it for the published version.

### What solution do you want to see ?

I see two options:

1. Allow for symlinking from within the plugin, similar to what is described [here](https://stackoverflow.com/questions/49980639/specify-alternate-project-level-readme-md-on-github/49981731#49981731). Probably not feasible,
2. Add a new tag `readme: true` which is allowed in a single note which is then renamed to `README.md` during publishing. This would need to throw an error if more than one note has the tag. 

### OS

Windows

### Plugin version

6.4.0

### Obsidian version & debug log

```bash session
SYSTEM INFO:
	Obsidian version: v1.3.7
	Installer version: v1.1.9
	Operating system: Windows 10 Pro 10.0.19045
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 28
	Plugins enabled: 28
		1: Diagrams v1.5.0
		2: Editing Toolbar v2.3.1
		3: Find orphaned files and broken links v1.9.0
		4: Hider v1.3.0
		5: Minimal Theme Settings v7.2.1
		6: Plugin Update Tracker v1.5.2
		7: Smart Typography v1.0.18
		8: Tag Wrangler v0.5.11
		9: Webpage HTML Export v1.6.0
		10: Templater v1.16.0
		11: Vault Changelog v0.1.0
		12: LanguageTool Integration v0.3.4
		13: Editor Syntax Highlight v0.1.3
		14: Better CodeBlock v1.0.8
		15: Dataview v0.5.56
		16: Linter v1.19.1
		17: No dupe leaves v0.0.11
		18: Advanced Tables v0.19.1
		19: Various Complements v8.3.3
		20: Natural Language Dates v0.6.1
		21: Awesome Image v0.1.2
		22: Omnisearch v1.15.2
		23: Text Extractor v0.4.6
		24: Badges v1.0.0
		25: Short links v1.1.4
		26: Callout Manager v1.0.1
		27: Obsidian Git v2.20.7
		28: Github Publisher v6.4.0

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

**Comment by Lisandra-dev** [comment]
I don't want to be mean but 
You can already create a README?

Like:
```
---
share: true
path: /
name: README
---
```
I do this for some of my project so…?

**Comment by tsievert** [comment]
Oh, that's great! Thanks!
I didn't realize it would work like this while reading the documentation!

**Comment by Lisandra-dev** [comment]
The plugin has a lot of possible configuration, uwu!

**Comment by tsievert** [comment]
Hm, this doesn't seem to work for me.
I've added 
```
share: true
path: /
name: README
```
but the filename stays the same.
Does this only work with the Mkdocs template?

**Comment by Lisandra-dev** [comment]
Normally, `path` should work with any parameters.

**Comment by tsievert** [comment]
Ah yes, that was the stepped I missed!
Thanks!
