### ISSUE TITLE
[Plugin][Bug]: Regex on filename / folder path does not function as expected

### ISSUE THREAD

**Issue by HighPriest** [ObsidianPublisher/obsidian-github-publisher#206]
### Issue validation

- [X] I checked the issue to prevent duplicate
- [X] I checked my configurations files and the documentation

### Command used

Upload all notes

### Plugin version

6.4.0

### Describe the bug

The Regex on filename / folder path has two issues for me:
1. Escaping special characters.
In regex `()` characters or `[]` have their special meaning. To match them in text we need to escape them with `\`. But adding the backslash to regex, throws an error `Folder path cannot contain the character `\`.
2. The tool does not check for trailing slash `/` after the folder path string has been cleaned up.
So, if I want to remove `hentai_stash` from `source/hentai_stash/hatsune_miku.mp3` I have to match for `/hentai_stash`, while `hentai_stash` should be sufficient. But even worse! While `hentai_stash` is going to throw an error. `hentai_stash/` is not going to match at all and fail silently!

Maybe related to #115 

### Minimal Reproducible Example

```markdown
^Explained in description
```

### Configuration

```JSON
No need
```

### Relevant log output
This comes up when folder name is used without preceding `/`
```bash session
HttpError: path contains a malformed path component: {"resource":"Commit","field":"path","code":"invalid"}
    at eval (plugin:obsidian-mkdocs-publisher:17:56241)
```

### OS

Windows

### Obsidian information

```bash session
SYSTEM INFO:
	Obsidian version: v1.3.7
	Installer version: v1.3.7
	Operating system: Windows 10
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 6
	Plugins enabled: 5
		1: Simple Embeds v1.14.1
		2: Tasks Calendar Wrapper v0.2.5
		3: Tasks v4.6.0
		4: ReadItLater v0.3.1
		5: Github Publisher v6.4.0
```

**Comment by Lisandra-dev** [comment]
Do you use:
- YAML
- Obsidian Path
- Or fixed folder ?

**Comment by HighPriest** [comment]
Obsidian path, dear @Lisandra-dev

**Comment by Lisandra-dev** [comment]
Hmm, I don't understand well this:
> The tool does not check for trailing slash / after the folder path string has been cleaned up.
So, if I want to remove hentai_stash from source/hentai_stash/hatsune_miku.mp3 I have to match for /hentai_stash, while hentai_stash should be sufficient. But even worse! While hentai_stash is going to throw an error. hentai_stash/ is not going to match at all and fail silently!

If I'm correct, the tool must use ` source/hentai_stash/hatsune_miku.mp3` → `source//hatsune_miku.mp3` in the "actual state" of the plugin regex, no ?
