### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by jt3k** [ObsidianPublisher/obsidian-github-publisher#21]
### Issue validation

- [X] My issue is not a question relative to [Material Mkdocs](https://squidfunk.github.io/mkdocs-material/) nor [Mkdocs](https://www.mkdocs.org/) (*[You can open a discussion to get more help!](https://github.com/squidfunk/mkdocs-material/discussions)*)
- [X] I checked the issue to prevent duplicate
- [X] I checked my configurations files and the documentation

### Workflow

Obsidian plugin 💠

### Describe the bug

i installed obsidian on my mac. Inside the settings, I found plugins and enabled the ObsidianPublisher plugin, which, as it seemed to me, should synchronize the vault to my repository.

### How to reproduce ?

1. install obsidian
1.1 Create vault using "quick start"
2. find the community plugins in the settings and enter ObsidianPublisher in the search
3. go to the settings of the ObsidianPublisher plugin and enter repository_name, github_name, and github_token
4. create a note
5. check if it appeared in the repository
6. press cmd+p and try to find the sync item.
7. click on all the items, and after each click, check if the note has been synchronized in the github repository

### Configuration

on macos I didn't find the ~/.obsidian folder
instead I found a folder
~/Documents/Obsidian Vault/.obsidian
I am attaching the data.json file. I removed the token from there for security

```json
{
  "githubRepo": "zettel-notes",
  "githubName": "jt3k",
  "GhToken": "<i cut this token before submitting the issue to github>",
  "shareKey": "share",
  "ExcludedFolder": "",
  "fileMenu": false,
  "editorMenu": false,
  "downloadedFolder": "fixed",
  "folderDefaultName": "",
  "yamlFolderKey": "",
  "rootFolder": "",
  "workflowName": "",
  "embedImage": true,
  "defaultImageFolder": "",
  "autoCleanUp": false,
  "autoCleanUpExcluded": "",
  "folderNote": false,
  "convertWikiLinks": false,
  "convertForGithub": false,
  "subFolder": "",
  "embedNotes": false,
  "copyLink": false,
  "mainLink": "",
  "linkRemover": "",
  "hardBreak": false,
  "logNotice": false,
  "convertDataview": true,
  "useFrontmatterTitle": false
}

```

### Relevant log output

```shell
Console output

app.js:1 Obsidian Developer Console
plugin:obsidian-mkdocs-publisher:2993 Github Publisher loaded
```
I opened obsidian and created a new note. then saved it with CMD+S.

I also clicked all the items of the ObsidianPublisher plugin in the command palette (cmd+p)
the console remained unchanged.

### OS

Android, MacOS

### Anything else?

in addition to macos, I also checked the plugin in android. and also did not succeed.
github_token used separate for android and for macos

**Comment by Mara-Li** [comment]
What do you mean by "clicking all the item" ?

**Comment by jt3k** [comment]
ah, I beg your pardon. I misunderstood the purpose of the plugin. from readme.md it was not immediately clear what exactly it does not do
