### ISSUE TITLE
Rely on Exclusion list for filtering. Synchronise everything option.

### ISSUE THREAD

**Issue by Lisandra-dev** [ObsidianPublisher/obsidian-github-publisher#210]
### Discussed in https://github.com/orgs/ObsidianPublisher/discussions/207

<div type='discussions-op-text'>

<sup>Originally posted by **HighPriest** August 24, 2023</sup>
Hi.
Would it fit your goals with this tool, to do not check for the `share key` if the config field is empty and rely on Exclusion list for files we do not want synchronised instead?

It would fit me much better if I could store my public files in one dir, private files in another.
If I work on something I do not want synchronised, I would rather give it a easily distinguishible `[DRAFT]` prefix to mark something not yet ready, than add unnecessary clutter to frontmatter.

So, to summarise. What I believe this requires are two things:
- Add regex support in Plugin Settings/Excluded Folder
- Add omitting of `share key` check if the field is empty</div>

**Comment by Lisandra-dev** [comment]
@HighPriest Can you try the v6.5.0-7 beta ? Ty

**Comment by HighPriest** [comment]
Tested. Works as expected.
Doesn't upload files with the prefix correctly.
Good idea with the switch dependent text field 🥇
