### ISSUE TITLE
[Plugin][FR]: File Menu Upload locks purge of unrelated directories

### ISSUE THREAD

**Issue by HighPriest** [ObsidianPublisher/obsidian-github-publisher#211]
### Issue validation

- [X] I checked the issue to prevent duplicate

### Is your feature related to a problem ?

#187 is on the same topic, but unrelated.

### What solution do you want to see ?

When Purge (Upload Config/Auto Clean Up) option is enabled and we use the File Menu Upload function on a directory, the Purge should only be executed on content which was previously located in this directory.

### OS

Windows

### Anything else?

Stuff to keep in mind:
- We might worry about content not getting auto-purged if the name of the directory is changed. This shouldn't be a point of focus, the person chooses to upload THIS directory. Stuff that is in the repo but unrelated, should not be touched. If someone wants to update the folder name, they should synchronise either the whole workspace, or parent folder. Otherwise we are forced to keep some history of dir names & path renames, which is insane :D

How I would handle this check:
- Run the "Upload dir" through Folder path rename
- Check if this renamed directory already exists in the repo
- If it exists, take all the other dirs and temporarily add them to excluded files and folders list of autoclean.
- Run Autoclean
- Merge, Commit, Push our directory

### Plugin version

v6.5.0-7

### Obsidian version & debug log

```bash session
SYSTEM INFO:
	Obsidian version: v1.3.7
	Installer version: v1.3.7
	Operating system: Windows 10 IoT Enterprise LTSC 2021 10.0.19044
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 6
	Plugins enabled: 5
		1: Simple Embeds v1.14.1
		2: Tasks Calendar Wrapper v0.2.5
		3: Tasks v4.6.0
		4: ReadItLater v0.3.1
		5: Github Publisher v6.5.0-7
```

**Comment by Lisandra-dev** [comment]
Can be complicated to do, as the folder path can be changed using option (with frontmatter) and It can't be get using the folder menu option :/
