### ISSUE TITLE
[Plugin][Bug]: Plugin can't be enabled on fresh install

### ISSUE THREAD

**Issue by hryggrbyr** [ObsidianPublisher/obsidian-github-publisher#213]
### Issue validation

- [X] I checked the issue to prevent duplicate
- [X] I checked my configurations files and the documentation

### Command used

Upload single current active note

### Plugin version

6.4.0

### Describe the bug

The commands are no longer available in the command pallet. I do not have _settings_ in the Community Plugin section of the main menu.

### How to reproduce ?

1. Create a new file in Obsidian
2. Paste in the content as above
3. Open the command pallet
4. Observe no _Github Publisher_ commands are visible.

### Minimal Reproducible Example

```markdown
---
title: "Test"
share: true
---
# Test
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
```

### Configuration

```JSON
export is not available as settings is not available
```

### OS

Android

### Obsidian information

```bash session
SYSTEM INFO:
	Operating system: android 13 (Google Pixel 4)
	Obsidian version: 1.4.6 (105)
	API version: v1.3.3
	Login status: logged in
	Catalyst license: none
	Live preview: off
	Legacy editor: off
	Base theme: dark
	Community theme: iA Writer v3.301
	Snippets enabled: 2
	Restricted mode: off
	Plugins installed: 13
	Plugins enabled: 13
		1: Metatable v0.14.6
		2: Periodic Notes v0.0.17
		3: Natural Language Dates v0.6.1
		4: QuickAdd v1.2.1
		5: TimeStamper v1.3.0
		6: Footnote Shortcut v0.1.3
		7: Find orphaned files and broken links v1.9.1
		8: Dataview v0.5.56
		9: Custom File Explorer sorting v1.8.2
		10: Clear Unused Images v1.1.0
		11: Calendar v1.5.10
		12: Apply Patterns v2.1.2
		13: Github Publisher v6.4.0

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

**Comment by Lisandra-dev** [comment]
Arf, on android i will have difficult to debug. Did you try on mobile ?
I have no problem on IOS…

**Comment by hryggrbyr** [comment]
Hi, no access to PC for a while. I'll check when I get my laptop back.

**Comment by Lisandra-dev** [comment]
Sorry for that :<

**Comment by Lisandra-dev** [comment]
By the way, could you try to install the brat plugin and the beta version? Maybe it was fixed by chance in the last version!

**Comment by Lisandra-dev** [comment]
Update : can repro the issue on new vault on iOS

**Comment by Lisandra-dev** [comment]
Fixed, you can install the plugin using BRAT
See: 

## BRAT
- Install [BRAT-42](https://obsidian.md/plugins?id=obsidian42-brat) using community plugin
- Open command palette : `BRAT: Plugins : Add a beta plugin for testing`
- Enter `https://github.com/ObsidianPublisher/obsidian-github-publisher`
- Click on [ADD PLUGIN]
- Wait for installation
- Go into Community Plugin
- Search "Github publisher"
- Enable!
