### ISSUE TITLE
[FR]: Add the ability to do custom Regex text transformation

### ISSUE THREAD

**Issue by yshalsager** [ObsidianPublisher/obsidian-github-publisher#22]
### Issue validation

- [X] My issue is not a question relative to [Material Mkdocs](https://squidfunk.github.io/mkdocs-material/) nor [Mkdocs](https://www.mkdocs.org/) (*[You can open a discussion to get more help!](https://github.com/squidfunk/mkdocs-material/discussions)*)
- [X] I checked the issue to prevent duplicate

### Workflow

Obsidian plugin 💠

### Is your feature related to a problem ?

I am using the plugin to push notes to my [digital garden](https://github.com/yshalsager/digital-garden) repo, which uses [Quartz](https://github.com/jackyzha0/quartz). However, Quartz doesn't like date formats in frontmatter like `2022-06-20 18:34`, and I have to regex it to remove the time part, then post date will be shown correctly. 

### What solution do you want to see ?

I would like the plugin to have an option for doing regex replace operations on text before copying note file. For example it can be a simple input field like other plugin settings, that user can set Regex replacements that will be performed on the file.

### Describe the alternative you've considered

Writing my own shell script that will run in CI modifying files.

### OS

Linux

**Comment by Mara-Li** [comment]
So your idea is a way to remove key in frontmatter? Or in *all* the contents? Why do you post an issue on Quartz ? The request seems to be pretty niche...

**Comment by yshalsager** [comment]
> So your idea is a way to remove key in frontmatter? Or in _all_ the contents? Why do you post an issue on Quartz ? The request seems to be pretty niche...

My idea is to add a general way to apply regex to note's text content while processing the note.

**Comment by Mara-Li** [comment]
It can be useful to censor things throught...

**Comment by yshalsager** [comment]
> It can be useful to censor things throught...

Yeah, this is one good usage too.

**Comment by Mara-Li** [comment]
feature added in 3.16 ! You can add multiple regex / text to be replaced :)
