### ISSUE TITLE
[Plugin][Bug]: share "false" also publishes note

### ISSUE THREAD

**Issue by anutator** [ObsidianPublisher/obsidian-github-publisher#225]
### Issue validation

- [X] I checked the issue to prevent duplicate
- [X] I checked my configurations files and the documentation

### Command used

Refresh published and upload new notes

### Plugin version

6.5.8

### Describe the bug

When I add tag `share: false` my note is also published. It is not published If I don't have this tag at all. I'd like to publish only with `share: true` or `share: yes`.
![2023-09-25_202442](https://github.com/ObsidianPublisher/obsidian-github-publisher/assets/25155468/17ff67eb-9906-4b7d-b638-1d7cabc5c697)

### How to reproduce ?

Add tag `share: false`.

### Minimal Reproducible Example

```markdown
On screenshot
```

### Configuration

```JSON
Config - https://github.com/anutator/blog/blob/main/mkdocs.yml
```

### Obsidian information

```bash session
1.4.13 version
```

**Comment by Lisandra-dev** [comment]
I love strange bug!
Thanks, will check this out
