### ISSUE TITLE
[Plugin][Bug]: Bug when share is empty

### ISSUE THREAD

**Issue by anareaty** [ObsidianPublisher/obsidian-github-publisher#226]
### Issue validation

- [X] I checked the issue to prevent duplicate
- [X] I checked my configurations files and the documentation

### Command used

Refresh published and upload new notes

### Plugin version

6.7.1

### Describe the bug

I was able to publish some individual notes just fine, but when I tried to reftesh and upload several notes at once, I got this bug.
```
plugin:obsidian-mkdocs-publisher:19 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'toString')
    at ce (plugin:obsidian-mkdocs-publisher:19:53057)
    at Ys.getAllFileWithPath (plugin:obsidian-mkdocs-publisher:28:10213)
    at eval (plugin:obsidian-mkdocs-publisher:23:20428)
    at Generator.next (<anonymous>)
    at eval (plugin:obsidian-mkdocs-publisher:2:871)
    at new Promise (<anonymous>)
    at m (plugin:obsidian-mkdocs-publisher:2:691)
    at so (plugin:obsidian-mkdocs-publisher:23:20333)
    at eval (plugin:obsidian-mkdocs-publisher:23:22746)
    at Generator.next (<anonymous>)
```
After some picking around I figured out the issue: one of my notes had the "share" property empty instead of true or false. After turning it to false the bug vanished. I looked at the code, and the thing is, it does not check if the property equals exactly null, and Obsidian does not treat null and false as the same thing anymore. It seems to be easy enough to fix, just add additional check for null along with undefined.

### How to reproduce ?

Create the note with the empty share property (can be created in the source mode) and try to share it of several notes at once.

### Minimal Reproducible Example

```markdown
-
```

### Configuration

```JSON
-
```

### Obsidian information

```bash session
-
```

**Comment by Lisandra-dev** [comment]
Oh ! Good catch umu! Will fix that asap :)

**Comment by Lisandra-dev** [comment]
Please, try the new version <3
