### ISSUE TITLE
[FR]: Copy inline tags to frontmatter

### ISSUE THREAD

**Issue by yshalsager** [ObsidianPublisher/obsidian-github-publisher#23]
### Issue validation

- [X] My issue is not a question relative to [Material Mkdocs](https://squidfunk.github.io/mkdocs-material/) nor [Mkdocs](https://www.mkdocs.org/) (*[You can open a discussion to get more help!](https://github.com/squidfunk/mkdocs-material/discussions)*)
- [X] I checked the issue to prevent duplicate

### Workflow

Obsidian plugin 💠

### Is your feature related to a problem ?

With some publishing websites like [Quartz](https://github.com/jackyzha0/quartz) and anything that uses Hugo, it's only possible to use tags if they are in frontmatter and inline tags doesn't work.

### What solution do you want to see ?

I think Publisher Plugin should have an option to add inline tags to frontmatter while processing file content.

### OS

Linux

### Anything else?

This can be done by:

- Getting inline tags `app.metadataCache.getFileCache(app.workspace.getActiveFile())?.tags?.map(t => t.tag.replace('#', '').replace('/', '_'))`.
- Appending tags to frontmatter `tags` key if it exists, or creating a new one with inline tags if it doesn't.

Instead of writing a code that does this from scratch I think [metaedit](https://github.com/chhoumann/MetaEdit) API can be utilized, this way by using `update`, `createYamlProperty`, `getPropertiesInFile` and `getPropertyValue`.

P.S. dataview can also get file tags, but it doesn't separate frontmatter and inline tags as far as I know.
`app.plugins.plugins.dataview.api.page(app.workspace.getActiveFile().path).file.tags`

**Comment by Mara-Li** [comment]
Excellent idea !! I never add this idea. I will take a look about the metaedit API and implement this asap
