### ISSUE TITLE
[Plugin][Bug]: Failed to parse expression when inline DV 

### ISSUE THREAD

**Issue by ooker777** [ObsidianPublisher/obsidian-github-publisher#235]
Make a new vault and a new note with this content:
```markdown
---
share: true
---
text before `=` text middle `random word`
```
Then the output with be: 
```markdown
`=` text middle `
```

For now I can work around by adding a space before the inline DQL:

```markdown
text before ` =` text middle `random word`
```

Plugins installed:
1: Github Publisher v6.10.2
2: Dataview v0.5.61

### Configuration

```JSON
{
  "github": {
    "branch": "main",
    "automaticallyMergePR": true,
    "api": {
      "tiersForApi": "Github Free/Pro/Team (default)",
      "hostname": ""
    },
    "workflow": {
      "name": "",
      "commitMessage": "[skip netlify] PUBLISHER"
    },
    "verifiedRepo": true
  },
  "upload": {
    "behavior": "obsidian",
    "subFolder": "",
    "defaultName": "docs",
    "rootFolder": "docs",
    "yamlFolderKey": "category",
    "frontmatterTitle": {
      "enable": true,
      "key": "filename"
    },
    "replaceTitle": [],
    "autoclean": {
      "enable": true,
      "excluded": [
        "docs/assets/js",
        "docs/assets/meta",
        "docs/assets/css",
        "tags.md",
        "graph.md"
      ]
    },
    "folderNote": {
      "enable": false,
      "rename": "index.md"
    },
    "metadataExtractorPath": "",
    "replacePath": []
  },
  "conversion": {
    "hardbreak": false,
    "dataview": true,
    "censorText": [
      {
        "entry": "10. PROJECT/ETERNITY/Wiki/Personnages",
        "replace": "",
        "after": true
      }
    ],
    "tags": {
      "inline": true,
      "exclude": [],
      "fields": []
    },
    "links": {
      "internal": true,
      "unshared": false,
      "wiki": true,
      "slugify": true
    }
  },
  "embed": {
    "attachments": true,
    "keySendFile": [
      "image"
    ],
    "notes": true,
    "folder": "docs/assets/attachments"
  },
  "tabsID": "github-configuration"
}
```

**Comment by Lisandra-dev** [comment]
The approache around dataview is pretty tricky and there are some problem with the last update, as the API wasn't updated correctly. 

I prefer to don't touch it for the moment, waiting for a proper update of the dataview API that will add a better support of in-lineDQL and DJS.

The inlineDQL support exists, but the API bug and I can't update to support it for the moment.

Maybe ask in the dataview issue to get some update ? 

https://github.com/blacksmithgu/obsidian-dataview/issues/2080

**Comment by Lisandra-dev** [comment]
Okay, with the last version of Dataview, it seems you **can't** use "text before `=` text middle `random word`"
![image](https://github.com/ObsidianPublisher/obsidian-github-publisher/assets/30244939/ff488d1b-d54b-4e16-9aee-14bd3e23f325)

Advice: 
- Change the inline key to something you won't use in your daily life 
- Use the space between the space

Close as it not a error from Obs-Publisher

**Comment by ooker777** [comment]
Hmm, is it possible to make the error intact? That is, if DV prints an error,then the output prints it and not trimming any text surrounding it. Or better print the query or simply `dataview incorrect query`

**Comment by Lisandra-dev** [comment]
No. It's not possible.

By the way. The file needs to be correct before you publish. The plugin won't correct this for you.

**Comment by ooker777** [comment]
Why is it not possible?

**Comment by Lisandra-dev** [comment]
Because the API doesn't work like that.
