### ISSUE TITLE
[Bug]: map is used on undefined in inlineTagsInText

### ISSUE THREAD

**Issue by yshalsager** [ObsidianPublisher/obsidian-github-publisher#24]
### Issue validation

- [X] My issue is not a question relative to [Material Mkdocs](https://squidfunk.github.io/mkdocs-material/) nor [Mkdocs](https://www.mkdocs.org/) (*[You can open a discussion to get more help!](https://github.com/squidfunk/mkdocs-material/discussions)*)
- [X] I checked the issue to prevent duplicate
- [X] I checked my configurations files and the documentation

### Workflow

Obsidian plugin 💠

### Describe the bug

In `addInlineTags` the plugin doesn't handle the case when there's no inline tags in a note correctly. This prevents the plugin from working properly while uploading all shared notes.

### Configuration

``

### OS

Linux

### Anything else?

![image](https://user-images.githubusercontent.com/17043808/186932141-481cdd30-e028-4947-9cce-deb093a48bd7.png)

**Comment by Mara-Li** [comment]
Oh, thanks, I completely forgot these case :'D

**Comment by yshalsager** [comment]
@Mara-Li Just updated to v4.0.1 and tried, still facing the same problem.

**Comment by Mara-Li** [comment]
Strange because i can't repro on my side 😭

**Comment by Mara-Li** [comment]
Okay, I found where is the problem !

**Comment by yshalsager** [comment]
@Mara-Li Awesome! It works fine now. Thanks once more :)
