### ISSUE TITLE
[FR]: Support Meta-bind views

### ISSUE THREAD

**Issue by mclearc** [ObsidianPublisher/obsidian-github-publisher#243]
### Issue validation

- [X] I checked the issue to prevent duplicate
- [X] My issue concern doesn't concern the [Mkdocs template](https://github.com/ObsidianPublisher/template-main/)

### Is your feature related to a problem ?

I am increasingly using the meta-bind plugin to view fields in markdown files. It would be wonderful if there was at least some support for this plugin. Here are the docs: https://mprojectscode.github.io/obsidian-meta-bind-plugin-docs/

Right now the github publication just publishes the raw code. 

### What solution do you want to see ?

I would like to see the data meta-bind pulls from the front matter in the main rendered file rather than the original meta-bind code. 

### OS

MacOS

### Anything else?

Meta-bind repo: https://github.com/mProjectsCode/obsidian-meta-bind-plugin
Meta-bind docs: https://mprojectscode.github.io/obsidian-meta-bind-plugin-docs/

### Plugin version

6.10.3

### Obsidian version & debug log

```bash session
SYSTEM INFO:
	Obsidian version: v1.4.16
	Installer version: v1.4.13
	Operating system: Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:45 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6020 23.1.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: off
	Legacy editor: off
	Base theme: adapt to system
	Community theme: Typomagical v1.9.1
	Snippets enabled: 14
	Restricted mode: off
	Plugins installed: 51
	Plugins enabled: 41
		1: Admonition v10.1.1
		2: Advanced Tables v0.19.1
		3: Auto Note Mover v1.2.0
		4: Better Word Count v0.10.0
		5: Buttons v0.4.19
		6: Dataview v0.5.64
		7: Dice Roller v10.4.0
		8: Excalidraw v1.9.28
		9: Excel to Markdown Table v0.4.0
		10: Export Image plugin v1.0.3
		11: Fantasy Statblocks v3.16.0
		12: Github Publisher v6.10.3
		13: Folder notes v1.6.11
		14: Icon Shortcodes v0.9.7
		15: JS Engine v0.0.5
		16: Meta Bind Plugin v0.7.2
		17: Initiative Tracker v12.4.2
		18: Webpage HTML Export v1.7.3
		19: Various Complements v9.1.0
		20: Text Mapper v1.0.0
		21: Text Format v2.2.8
		22: Settings Search v1.3.10
		23: Table Extended v1.6.1
		24: Quick Switcher++ v3.3.8
		25: Pandoc Plugin v0.4.1
		26: Obsidian Enhancing Export v1.9.2
		27: Obsidian42 - BRAT v0.7.1
		28: Obsidian Leaflet v6.0.0
		29: JSON/CSV Importer v0.31.2
		30: Tag Wrangler v0.6.1
		31: Link with alias v1.0.7
		32: Note Auto Creator v10
		33: Iconize v2.7.3
		34: Style Settings v1.0.7
		35: Hover Editor v0.11.15
		36: Hover External Link Plugin v1.0.0
		37: Custom Frames v2.4.6
		38: CSS Editor v0.5.0
		39: Text Generator v0.5.13
		40: Image Toolkit v1.4.0
		41: Linter v1.20.1

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

**Comment by Lisandra-dev** [comment]
Don't think it's possible, as I don't have any api to introduce it. Moreover, I don't use it and don't want to do a lot of circonvolution to get the API of metabind to work.

**Comment by Lisandra-dev** [comment]
After some check, maybe you could use [this](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/blob/master/Publish.js) ? 
I'm not sure if it works with mkdocs, to be honest.
