### ISSUE TITLE
[Bug]: plugin fails to be loaded

### ISSUE THREAD

**Issue by javoerro** [ObsidianPublisher/obsidian-github-publisher#247]
### Issue validation

- [X] I checked the issue to prevent duplicate
- [X] I checked my configurations files and the documentation
- [X] My issue concern doesn't concern the [Mkdocs template](https://github.com/ObsidianPublisher/template-main/)

### Command used

Test the connection to the configured repository

### Plugin version

6.11.1

### Describe the bug

I hope this message finds you well. I am writing to report an issue I encountered while attempting to install the plugin. After installing the plugin, the commands and options associated with it do not load. Consequently, when following the installation instructions provided at [](https://obsidian-publisher.netlify.app/template/#installation-steps), I am unable to proceed with Step 5, which involves configuring the plugin's options by setting the repository name, GitHub username, GitHub token, and branch name.

To provide further context, none of the eight commands listed below appear in the command palette:

Upload single current active note
Upload all notes
Upload unpublished notes
Refresh published and upload new notes
Refresh all published notes
Purge depublished and deleted files
Test the connection to the configured repository
Check the rate limit of the GitHub API
I am using Obsidian version 1.4.16.

Thank you for your attention to this matter, and I appreciate any assistance you can provide in resolving this issue.

### How to reproduce ?

In Obsidian version 1.4.16:
Open new vault
Turn on community plugins
Search for Github Publisher
Install and enable

### Minimal Reproducible Example

```markdown
plugin fails to be loaded
```

### Configuration

```JSON
plugin fails to be loaded
```

### Relevant log output

```bash session
[GITHUB PUBLISHER] v.6.11.1 (lang: en) loaded
VM214 plugin:obsidia…mkdocs-publisher:19 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'plugin')
    at H (plugin:obsidian-mkdo…-publisher:19:67205)
    at Cr.eval (plugin:obsidian-mkdo…publisher:36:104630)
    at Generator.next (<anonymous>)
    at r (plugin:obsidian-mkdocs-publisher:2:729)
VM214 plugin:obsidia…mkdocs-publisher:36 [Github Publisher] unloaded
```

### OS

Windows

### Obsidian information

```bash session
SYSTEM INFO:
	Obsidian version: v1.4.16
	Installer version: v1.4.16
	Operating system: Windows 10 Enterprise 10.0.19045
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 2
	Plugins enabled: 2
		1: Webpage HTML Export v1.7.3
		2: Github Publisher v6.11.1

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

**Comment by Lisandra-dev** [comment]
Strange, I would think that my last fix fixed the issue. Will working on it ASAP.
