### ISSUE TITLE
[FR]: GitHub Actions support

### ISSUE THREAD

**Issue by jericjan** [ObsidianPublisher/obsidian-github-publisher#248]
### Issue validation

- [X] I checked the issue to prevent duplicate
- [X] My issue concern doesn't concern the [Mkdocs template](https://github.com/ObsidianPublisher/template-main/)

### Is your feature related to a problem ?

I'm currently exporting at least 600 files with this plugin. It might just be my internet and hardware, but it feels very slow, and also redundant, since I already have a 1:1 backup of my vault to a different repo. 

### What solution do you want to see ?

I have no idea if it's possible, but a github action would be perfect. After my periodic backup occurs, the obsidion-publisher action starts and does its job according to a provided config file.

### Describe the alternative you've considered

If that's a no-go, an option to export to a local folder would be nice. That avoids having to make hundreds of commits.

### OS

Windows

### Anything else?

Before this, I was using the [obsidian-to-hugo-pages](https://github.com/marketplace/actions/obsidian-to-hugo-pages) action by haxrob. It's very fast by comparison, but it lacks a ton of features like dataview support and folder note renaming, 

### Plugin version

v6.11.2

### Obsidian version & debug log

```bash session
SYSTEM INFO:
	Obsidian version: v1.4.16
	Installer version: v1.4.13
	Operating system: Windows 10 Pro 10.0.19041
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal v7.2.1
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 36
	Plugins enabled: 35
		1: Dangerzone Writing v0.0.11
		2: Calendar v1.5.10
		3: File Cleaner v0.1.5
		4: Simple Embeds v1.14.1
		5: Obsidian Clipper v0.2.4
		6: 3D Graph v1.0.3
		7: ProZen v0.3
		8: Obsidian Git v2.22.0
		9: Folder Note v0.7.3
		10: Advanced Slides v1.20.0
		11: Solve v0.4.1
		12: Advanced Tables v0.19.1
		13: Importer v1.3.1
		14: Dangling links v0.3.0
		15: Tag Wrangler v0.5.12
		16: Omnisearch v1.17.1
		17: Pandoc Plugin v0.4.1
		18: Media Extended v2.11.1
		19: Regex Find/Replace v1.2.0
		20: Kanban v1.5.3
		21: Unitade v1.0.2
		22: Note Refactor v1.8.2
		23: Dataview v0.5.64
		24: Link Tree v1.0.0
		25: DataLoom v8.11.3
		26: Style Settings v1.0.7
		27: Minimal Theme Settings v7.3.0
		28: Prettier Format v0.1.1
		29: Editor Syntax Highlight v0.1.3
		30: Task Collector (TC) v1.0.12
		31: Obsidian Charts v3.8.2
		32: Excel v1.3.11
		33: File Cooker v1.8.1
		34: Linter v1.20.1
		35: Github Publisher v6.11.2

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

**Comment by Lisandra-dev** [comment]
I'm sorry I won't support that.
More over an external methods won't support 99% things included in the plugin. For example, Dataview.

It can be possible to write a python or a node package for some part of the plugin but I won't do it.

There are already warning about the time that the plugin can take.

You can send already by folder so I think you can send folder by folder if possible.
