### ISSUE TITLE
[FR]: Copy tags improvement: Add the ability to copy dataview simple values to tags

### ISSUE THREAD

**Issue by yshalsager** [ObsidianPublisher/obsidian-github-publisher#26]
### Issue validation

- [X] My issue is not a question relative to [Material Mkdocs](https://squidfunk.github.io/mkdocs-material/) nor [Mkdocs](https://www.mkdocs.org/) (*[You can open a discussion to get more help!](https://github.com/squidfunk/mkdocs-material/discussions)*)
- [X] I checked the issue to prevent duplicate

### Workflow

Obsidian plugin 💠

### What solution do you want to see ?

Some people heavily depends on dataview annotations for categorizing topics instead of tags. I think a super useful addition would be having the ability to copy pre-defined dataview inline fields link text value(s).

For example, if I have the page with the following:

```
---  
created: 2021-12-28 00:00  
updated: 2021-12-28 00:00  
title: youtube-dl download subtitle only  
share: true  
website: en/notes  
---  
  
# youtube-dl download subtitle only  
  
Status:: #notes/archives  
Link: <https://superuser.com/a/927532>  
Knowledge:: [Linux](Linux), [Tools](Tools),
```

By setting `Knowledge` as the field to be copied, the processed note should have:

```
tags:
  - Linux
  - Tools
```

### OS

Linux

### Anything else?

- The option should be able to handle having single or multiple dataview link objects, because as far as I know it can be `Link` or `Array`.

**Comment by Mara-Li** [comment]
I think this suggestion is irrelevant for the plugin. It needs to handle too much parameters/regex. If you need to add tags to your note with using dataview, just edit it with using templater/quick add.

**Comment by yshalsager** [comment]
> I think this suggestion is irrelevant for the plugin. It needs to handle too much parameters/regex. If you need to add tags to your note with using dataview, just edit it with using templater/quick add.

Hmm, shouldn't it be easy enough to utilize dataview API to do this instead of relying on regex?

```
{
    ...
    "created": "2021-12-28 00:00",
    "updated": "2021-12-28 00:00",
    "title": "youtube-dl download subtitle only",
    "share": true,
    "website": "en/notes",
    "status": "#notes/archives",
    "knowledge": { // Link
        "path": "Linux.md",
        "type": "file",
        "embed": false
    }
}
```

**Comment by Mara-Li** [comment]
How can you notice that the knowledge is a link, tag, string, list... TBH i don't think it's useful/relevant in the purpose of the plugin?

**Comment by yshalsager** [comment]
> How can you notice that the knowledge is a link, tag, string, list... TBH i don't think it's useful/relevant in the purpose of the plugin?

Simply by checking `typeof`?
- link => use its text.
- string => use as is.
- tag => use without spaces or slashes.
- array => deal with each as previous.

The point of my suggestion is to improve reachability of content on platforms like Hugo by appending certain DV inline fields to tags, since inline fields are useless outside obsidian. So, it's kind of sub-feature of inline tags to tags feature.

Honestly, I think it's relevant to the plugin note content process part.

**Comment by Mara-Li** [comment]
But you could add the tags directly using templater ?

**Comment by yshalsager** [comment]
> But you could add the tags directly using templater ?

That's totally possible, but this approach will have some problems in my opinion:
- It will pollute tags for someone that heavily depends on dataview annotations for categorizing topics instead of tags.
- It works only well when I already know where does this note belong.
- The tag be always added to the note.

**Comment by Mara-Li** [comment]
For me, dataview is not designed to be published. I don't want to add theses option because it will polute more and more the settings, as I need to add : 
- Textaera to get the field
- Add a way to exclude value
- Call dataview API to get the internal field
- Check every value of the choosen fields, as string, link, or array 
- Get only the string part as an array, filter the list with excluded value
- Modify again the frontmatter with parseYaml and stringify. 

This will add more and more options to just set tags based on dataview value...

**Comment by Mara-Li** [comment]
Hmmm, after summarize this, finally i think it can be usefull throught Publisher.

Do you have the dataview function to get inline metadata ?

**Comment by yshalsager** [comment]
> Hmmm, after summarize this, finally i think it can be usefull throught Publisher.
> 
> Do you have the dataview function to get inline metadata ?

No idea if there's such function to get only inline metadata, but I think there's no need to filter only inline, as the workflow can simply go like: values from users and access value directly using `dataview.page("current page path")[key]`

**Comment by Mara-Li** [comment]
I updated in **beta** (to try this time ;) the plugin ! Could you please try / beta test this function ? :)

**Comment by yshalsager** [comment]
> I updated in **beta** (to try this time ;) the plugin ! Could you please try / beta test this function ? :)

Awesome!

Just gave it a try, but apparently it removes other tags copied by inline to tags feature by mistake?
Here's an [example](https://github.com/yshalsager/digital-garden/pull/27/files)

**Comment by Mara-Li** [comment]
Thanks you for this reply and bug issue ! I fixed it :)

**Comment by yshalsager** [comment]
> Thanks you for this reply and bug issue ! I fixed it :) Could you please try the last update ? :)

Thanks for the quick fix! Works perfectly now.
