### ISSUE TITLE
[FR]: Support for git wiki

### ISSUE THREAD

**Issue by AlphaFoxz** [ObsidianPublisher/obsidian-github-publisher#261]
### Issue validation

- [X] I checked the issue to prevent duplicate
- [X] My issue concern doesn't concern the [Mkdocs template](https://github.com/ObsidianPublisher/template-main/)

### Is your feature related to a problem ?

my repo has wiki. but can't build a connection.

### What solution do you want to see ?

Support for git wiki

### OS

Windows

### Anything else?

In `/Github/branches.ts` the function `async checkRepository` throwed a 404 err.
because api [oneboot.wiki](https://api.github.com/repos/AlphaFoxz/oneboot.wiki) returned "Not Found"

But when repo name ends with `.wiki`. It can be check from another api that without `.wiki`.
such as [oneboot(without .wiki)](https://api.github.com/repos/AlphaFoxz/oneboot)

there is attribute `has_wiki: true`

### Plugin version

6.12.1

### Obsidian version & debug log

```bash session
Obsidian version v1.4.16
```

**Comment by Lisandra-dev** [comment]
Please, read the docs. 
You need to use the repo name, not `.wiki`.

**Comment by Lisandra-dev** [comment]
Doesn't seems possible, I can't found the API in Github Octokit.
Maybe we need to wait for an update to get .wiki repo :/

**Comment by Lisandra-dev** [comment]
A solution is to use a github actions to mirror folder : https://github.com/marketplace/actions/github-wiki-action

**Comment by AlphaFoxz** [comment]
> A solution is to use a github actions to mirror folder : https://github.com/marketplace/actions/github-wiki-action

thx a lot! Its helpful

**Comment by Lisandra-dev** [comment]
If you success to do it, you can share your workflow in the discussion!
