### ISSUE TITLE
[Bug]: icannot git up

### ISSUE THREAD

**Issue by hxer520** [ObsidianPublisher/obsidian-github-publisher#27]
### Issue validation

- [X] My issue is not a question relative to [Material Mkdocs](https://squidfunk.github.io/mkdocs-material/) nor [Mkdocs](https://www.mkdocs.org/) (*[You can open a discussion to get more help!](https://github.com/squidfunk/mkdocs-material/discussions)*)
- [X] I checked the issue to prevent duplicate
- [X] I checked my configurations files and the documentation

### Workflow

Obsidian plugin 💠

### Describe the bug

<img width="358" alt="image" src="https://user-images.githubusercontent.com/12802662/187468613-3287ef0e-64aa-4d5c-b202-8c39e2cd6a5f.png">

# plugin cannot git push to my repo

<img width="1073" alt="image" src="https://user-images.githubusercontent.com/12802662/187468844-9f3946b3-7026-43fd-ab25-1a0aaf6bb487.png">

# i alread init my docsify by my PC

<img width="349" alt="image" src="https://user-images.githubusercontent.com/12802662/187469143-3662b70e-ecd3-4caf-8598-437b33feea89.png">

# i don‘t know how to use the plugin

### Configuration

i can't find reason to the question T_T

**Comment by Lisandra-dev** [comment]
Please, read the doc.

**Comment by hxer520** [comment]
i don't understand ,i stay by stay from doc ,but can't used

**Comment by Lisandra-dev** [comment]
The plugin doesn't git up and doesn't work for synchronise git. It allows to send file on a github repository using Github REST API.
