### ISSUE TITLE
"Share all files" on, but still need to add a "share: true" property

### ISSUE THREAD

**Issue by Lisandra-dev** [ObsidianPublisher/obsidian-github-publisher#271]
### Discussed in https://github.com/orgs/ObsidianPublisher/discussions/270

<div type='discussions-op-text'>

<sup>Originally posted by **WolfieKnee** January  8, 2024</sup>
Hi - I'm getting inconsistency behaviour when using the "share all files" settings in the plugin: 
- If I add new file to my vault and run a sync it doesn't work
- if I add a share: true property it syncs fine

Am I expecting the correct behaviour or is there potentially something wrong here?

thanks*
Dave

* and thanks for a great tool!

obsidian 1.5.3 on ubuntu 22.X with plugin 6.11.5</div>

**Comment by Lisandra-dev** [comment]
FIXED in 6.13.0
→ Version added a file stack for debugging (allow mobile debugging) 
→ Bug caused by empty frontmatter and obsidian returning "undefined".

**Comment by WolfieKnee** [comment]
Happy to confirm this fixed issue - thanks!
