### ISSUE TITLE
[Bug]: Files uploading with empty content

### ISSUE THREAD

**Issue by KorvinSzanto** [ObsidianPublisher/obsidian-github-publisher#276]
### Issue validation

- [X] I checked the issue to prevent duplicate
- [X] I checked my configurations files and the documentation
- [X] My issue concern doesn't concern the [Mkdocs template](https://github.com/ObsidianPublisher/template-main/)

### Command used

Upload all notes

### Plugin version

6.13.5

### Describe the bug

Uploading new notes leads to files uploaded with effectively empty content:
```md
---
{}
---
```

### How to reproduce ?

1. Enable share all notes
2. Upload all notes

### Minimal Reproducible Example

```markdown
## This file is empty
- Foo
- Baz
```

### Configuration

```JSON
{
  "github": {
    "branch": "main",
    "automaticallyMergePR": true,
    "tokenPath": "%configDir%/plugins/%pluginID%/env",
    "api": {
      "tiersForApi": "Github Free/Pro/Team (default)",
      "hostname": ""
    },
    "workflow": {
      "commitMessage": "[PUBLISHER] Merge",
      "name": ""
    },
    "verifiedRepo": true
  },
  "upload": {
    "behavior": "obsidian",
    "defaultName": "",
    "rootFolder": "",
    "yamlFolderKey": "",
    "frontmatterTitle": {
      "enable": false,
      "key": "title"
    },
    "replaceTitle": [],
    "replacePath": [],
    "autoclean": {
      "enable": false,
      "excluded": []
    },
    "folderNote": {
      "enable": false,
      "rename": "index.md",
      "addTitle": {
        "enable": false,
        "key": "title"
      }
    },
    "metadataExtractorPath": ""
  },
  "conversion": {
    "hardbreak": false,
    "dataview": true,
    "censorText": [],
    "tags": {
      "inline": false,
      "exclude": [],
      "fields": []
    },
    "links": {
      "internal": false,
      "unshared": true,
      "wiki": false,
      "slugify": false
    }
  },
  "embed": {
    "attachments": true,
    "overrideAttachments": [],
    "keySendFile": [],
    "notes": false,
    "folder": "",
    "convertEmbedToLinks": "keep",
    "charConvert": "->"
  }
}
```

### OS

MacOS

### Anything else?

Some files upload properly but others are blank/empty.

### Obsidian information

```bash session
SYSTEM INFO:
	Obsidian version: v1.5.3
	Installer version: v1.4.16
	Operating system: Darwin Kernel Version 23.2.0: Wed Nov 15 21:55:06 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6020 23.2.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 2
	Plugins enabled: 1
		1: Github Publisher v6.13.5

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```
```

**Comment by Lisandra-dev** [comment]
Do you share file without sharing key?

**Comment by KorvinSzanto** [comment]
> Do you share file without sharing key?
I don't understand the question, can you ask in a different way?
I have the plugin configured to share all files and to use the obsidian path as the key.

**Comment by Lisandra-dev** [comment]
The option is in the last tabs, first option. Share without key, tabs "plugins settings"

**Comment by KorvinSzanto** [comment]
Yeah I have "Share all files" enabled which mentions the key, I don't see a setting called "Share without key" otherwise:
![image](https://github.com/ObsidianPublisher/obsidian-github-publisher/assets/1007419/1f45c042-4313-489b-a4a4-fece0c21df44)

**Comment by Lisandra-dev** [comment]
Well, it's just a resume of the option ^^". 
I named it like that in the `data.json` file, so I use it as default when asking. Sorry ^^"

**Comment by Lisandra-dev** [comment]
Should be fixed!
