### ISSUE TITLE
[FR]: Add ability to specify frontmatter fields that reference files

### ISSUE THREAD

**Issue by krivaten** [ObsidianPublisher/obsidian-github-publisher#28]
### Issue validation

- [X] My issue is not a question relative to [Material Mkdocs](https://squidfunk.github.io/mkdocs-material/) nor [Mkdocs](https://www.mkdocs.org/) (*[You can open a discussion to get more help!](https://github.com/squidfunk/mkdocs-material/discussions)*)
- [X] I checked the issue to prevent duplicate

### Workflow

Obsidian plugin 💠

### Is your feature related to a problem ?

No.

### What solution do you want to see ?

I use a plugin simply called "Banners" ([Link](https://github.com/noatpad/obsidian-banners)). It allows me to specify an image using a frontmatter field (i.e., `banner`) which displays above my note. It would be nice if I could also use this field to identify the featured image of a particular note.

My idea is to allow users to specify frontmatter fields that are used to reference images/files that, if present, would trigger your plugin to send that file along with the Merge Request as well.

### Describe the alternative you've considered

I have thought of:

1. Just not having featured images 
    - But that's not as pretty!
3. Add the image at the top of the note
    - This would look weird with the Banners plugin (Though, I know that is not your problem)
    - I would have a hard time doing any custom styling for that image, especially if I wanted it to display elsewhere on my webpage
4. Use a combination of uploading the file manually and then use text replace to get the URL right
    - This could be a pain to setup and be prone to issues

### OS

MacOS

### Anything else?

I'm loving this plugin. Solves so many problems I was having. Thank you!

**Comment by Lisandra-dev** [comment]
Nice idea, can be useful ! I will add it today :).

**Comment by Lisandra-dev** [comment]
Please, could you try with the last BRAT beta for this FR ? 
Close the issue if you don't see any error :)

**Comment by krivaten** [comment]
My goodness that is a fast turnaround! Wasn't aware of BRAT, but got that installed and _voila_ it works beautifully! Thank you so much!
