### ISSUE TITLE
[Bug]: Embedded links to images are removed by plugin during publishing

### ISSUE THREAD

**Issue by alexeystalker** [ObsidianPublisher/obsidian-github-publisher#30]
### Issue validation

- [X] My issue is not a question relative to [Material Mkdocs](https://squidfunk.github.io/mkdocs-material/) nor [Mkdocs](https://www.mkdocs.org/) (*[You can open a discussion to get more help!](https://github.com/squidfunk/mkdocs-material/discussions)*)
- [X] I checked the issue to prevent duplicate
- [X] I checked my configurations files and the documentation

### Workflow

Obsidian plugin 💠

### Describe the bug

When I publish a note with a Obsidian plugin (release 4.2.1), and a note has image embedded with a wiki link `![[image file name.png]]`, link is removed from an .md file sent to github. "EmbedImage" option is on.
Definitely this was working for me using some previous release, but I did not notice the release that broke embedding, but the last one (4.2.1) has this bug.

### How to reproduce ?

1. Make a note with an embedded image in an Obsidian vault and mark it with `share: true` in a frontmatter, or select an already shared note with an embedded image. Image should be embedded with a wikilink (`![[some image.png]]`).
2. Publish it via Obsidian Plugin.
3. Look at the published file in a github repository - image link is removed.

### Configuration

{
  "githubRepo": "---",
  "githubName": "---",
  "GhToken": "---",
  "shareKey": "share",
  "ExcludedFolder": "",
  "fileMenu": false,
  "editorMenu": false,
  "downloadedFolder": "obsidian",
  "folderDefaultName": "docs",
  "yamlFolderKey": "",
  "rootFolder": "",
  "workflowName": "",
  "embedImage": true,
  "defaultImageFolder": "docs/images",
  "autoCleanUp": true,
  "autoCleanUpExcluded": "docs/assets/logo",
  "folderNote": false,
  "convertWikiLinks": false,
  "convertForGithub": false,
  "subFolder": "",
  "embedNotes": false,
  "copyLink": false,
  "mainLink": "",
  "linkRemover": "",
  "hardBreak": false,
  "logNotice": false,
  "convertDataview": false,
  "useFrontmatterTitle": false,
  "censorText": [],
  "inlineTags": false,
  "dataviewFields": [],
  "excludeDataviewValue": [],
  "metadataFileFields": [],
  "frontmatterTitleKey": "title",
  "transferEmbedded": true
}

### OS

Windows

**Comment by Lisandra-dev** [comment]
Woups, Sorry. Something maybe explode during my feature add

**Comment by Lisandra-dev** [comment]
Huh, in fact you need to allow the Sharing of embeded note

**Comment by alexeystalker** [comment]
I've turned "embedNotes" to true, but this did not help.

**Comment by Lisandra-dev** [comment]
I will check that today ! Sorry for the inconvenience

**Comment by alexeystalker** [comment]
Thanks for quick response! I'll be waiting for the news.

**Comment by Lisandra-dev** [comment]
What did I do agaaaaaaaaaain (sorry, I whine because I looking for the things I missed up)

**Comment by Lisandra-dev** [comment]
Okay, found it. Should it fixed in the next beta release !

**Comment by alexeystalker** [comment]
Thanks for quick fix!
