### ISSUE TITLE
[Bug]: Internal links grayed out / displayed as class=" not found" on GH Pages

### ISSUE THREAD

**Issue by AudioLotus** [ObsidianPublisher/obsidian-github-publisher#304]
### Issue validation

- [X] I checked the issue to prevent duplicate
- [X] I checked my configurations files and the documentation
- [X] My issue concern doesn't concern the [Mkdocs template](https://github.com/ObsidianPublisher/template-main/)

### Command used

Upload all notes, Upload single current active note, Refresh all published notes

### Plugin version

6.14.1

### Describe the bug

Regardless of which settings I use, when I publish a note, internal links don't seem to work. They appear greyed out and not able to be clicked.

In plugin settings I've tried both "Internal Links" and "Convert Wikilinks to MDLinks", neither of which worked after republishing. 

### How to reproduce ?

1. Add wiki link in md file using "relative path to file" setting in Obsidian
2. Set frontmatter to share:true
3. Publish single note
4. View note on Github Page

### Minimal Reproducible Example

```markdown
---
activity_type:
  - Raid
activity_name: Last Wish
aliases:
  - Last Wish Intro
tags:
  - intro
share: "true"
---

----

## Table of Contents

[[#Mechanics]]
[[#Encounters]]
[[#Bonus Chests]]
[[#Tools]]

----

## Mechanics

So, in my opinion, Last Wish doesn't really have a consistent set of building mechanics like others do. However, you'll see the same bits and pieces pop up every so often.

**Symbols:** One thing that appears often are sets of symbols with either a bird, snake, fish, or dragon in black on a pale green background. Here are the ones I personally use:

![[../../Attachments/LW Images/LW-symbols.png|callouts for symbols]]

**Taken Blights**: in a few encounter you'll see some taken orbs in pillars of light. When these are picked up they give a **Taken Strength** debuff which will kill you if you get more than two stacks.

**Plates**: I mean really, that's what they are. These are floating platforms you stand on that will hurt you over time.

Also there's a **Wishing Wall** found past Kalli's arena after you jump up some rocks:

![[../../Attachments/LW Images/Wishing Wall.jpeg|The Wishing Wall|ctr]]

---

## Encounters

##### [[1. Kalli, the Corrupted|Kalli, the Corrupted]]

Let's match some symbols, cleanse some plates, and hide in closets!

##### [[2. Shuro Chi, The Corrupted|Shuro Chi]]

Laser almonds and puzzles abound!

##### [[3. Morgeth, the Spirekeeper|Morgeth]]

Take strength, get buffs, kill kill kill

##### [[4. The Vault|Vault]]

Oh God oh fuck.

##### [[5. Riven of a Thousand Voices|Riven of a Thousand Voices]]

Poke her toes or shoot her face, cheese style!

##### [[6. Riven's Heart|Riven's Heart]]

Carry an orb in a relay race, take strengths, hope for the best!

----

## Bonus Chests

First one right after Kalli below one of the thin platforms you have to cross. You'll have to jump down and land in the entrance. It'll take a few tries

Second one is right after Shuro Chi, on a cliff. When you see the portal to Morgeth, you've gone slightly too far. It'll be out of one of the side doors where you have to jump up some trees and over a gap to get to.

----

## Tools

This is a *really* helpful tool for the Vault encounter.

https://the-vault.netlify.app/

----

Wanna see other guides? Check out [[../../index|the rest of what I have!]]
```

### Configuration

```JSON
{
  "github": {
    "branch": "main",
    "automaticallyMergePR": false,
    "dryRun": {
      "enable": false,
      "folderName": "github-publisher"
    },
    "tokenPath": "%configDir%/plugins/%pluginID%/env",
    "api": {
      "tiersForApi": "Github Free/Pro/Team (default)",
      "hostname": ""
    },
    "workflow": {
      "commitMessage": "[PUBLISHER] Merge",
      "name": ""
    },
    "verifiedRepo": true
  },
  "upload": {
    "behavior": "obsidian",
    "defaultName": "docs",
    "rootFolder": "",
    "yamlFolderKey": "",
    "frontmatterTitle": {
      "enable": false,
      "key": "title"
    },
    "replaceTitle": [],
    "replacePath": [],
    "autoclean": {
      "enable": true,
      "excluded": [
        "docs/assets",
        "tags.md"
      ]
    },
    "folderNote": {
      "enable": false,
      "rename": "index.md",
      "addTitle": {
        "enable": false,
        "key": "title"
      }
    },
    "metadataExtractorPath": ""
  },
  "conversion": {
    "hardbreak": true,
    "dataview": true,
    "censorText": [],
    "tags": {
      "inline": false,
      "exclude": [],
      "fields": []
    },
    "links": {
      "internal": true,
      "unshared": false,
      "wiki": false,
      "slugify": "strict"
    }
  },
  "embed": {
    "attachments": true,
    "overrideAttachments": [],
    "keySendFile": [],
    "notes": false,
    "folder": "docs/assets/img",
    "convertEmbedToLinks": "keep",
    "charConvert": "->",
    "useObsidianFolder": false
  }
}
```

### Relevant log output

```bash session
-
```

### OS

Windows

### Anything else?

![Screenshot 2024-02-06 170150](https://github.com/ObsidianPublisher/obsidian-github-publisher/assets/93493187/9685383c-1ae9-4111-ae4c-a6aa6e6a0bea)
![Screenshot 2024-02-06 170229](https://github.com/ObsidianPublisher/obsidian-github-publisher/assets/93493187/a82904c3-5ace-4747-87f2-1cb8485da7a6)

Link to site: https://audiolotus.github.io/FlwrzD2/Raids/Last%20Wish/0.%20Intro%20to%20Last%20Wish/

Link to repo: https://github.com/AudioLotus/FlwrzD2

### Obsidian information

```bash session
SYSTEM INFO:
	Obsidian version: v1.5.3
	Installer version: v1.5.3
	Operating system: Windows 10 Pro 10.0.22631
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Base theme: dark
	Community theme: Obsidian Nord v0.2.0
	Snippets enabled: 8
	Restricted mode: off
	Plugins installed: 8
	Plugins enabled: 8
		1: Style Settings v1.0.7
		2: Dataview v0.5.64
		3: Tag Wrangler v0.6.1
		4: Admonition v10.1.2
		5: Linter v1.22.0
		6: Metadata Menu v0.7.7
		7: Editing Toolbar v2.4.0
		8: Github Publisher v6.14.1

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

**Comment by Lisandra-dev** [comment]
Is the links works in GitHub when you use markdown links ?

**Comment by AudioLotus** [comment]
Nope. sadly

```The  main branch of FlwrzD2 does not contain the path docs/Raids/Last%20Wish3.%2520Morgeth,%2520the%2520Spirekeeper.md.```

is what I get when I view the .md in the repo

It looks like when the plugin converts the page, it's adding the extra entity to it making %2520 vs %20 or something similar

**Comment by Lisandra-dev** [comment]
Yeah, I think the problem with your page is the extra `5.` before.

Could you try to use the renaming frontmatter function? It allows to rename file in the repo.
You need to use the title key to keep the original name

**Comment by AudioLotus** [comment]
Pardon my ignorance here cause I couldn't find it in the documentation, but what would those properties be?

**Comment by AudioLotus** [comment]
Small update, as I found the examples in the documentation. I tried different combos in both the title field and filename field. I even tried them separately to see what would happen. 

I followed the example in the documentation and wrote mine out the way it said. The page title itself would change on the hosted page but the file was not renamed nor were the links changed in other pages.

I tried removing the "." From the filename as well to just include a "-" but that hasn't worked either. 

I'm unsure what to do next really.

**Comment by Lisandra-dev** [comment]
Did you enable the renaming in the settings? It's not enabled by default.

**Comment by AudioLotus** [comment]
Ah that makes sense. I misinterpreted what the button was saying in settings.

It changed the filename successfully, but the links to the test page still aren't working. They show the correct filename in the inspector view on Firefox, but still show "not found" and can't be clicked. 

I'm so sorry for all this hassle!

**Comment by Lisandra-dev** [comment]
Could you please try to use the markdown links conversion and see if in github the links works, now?

**Comment by AudioLotus** [comment]
So in the repo itself it works now, but not on the published page.

**Comment by Lisandra-dev** [comment]
So it's an issue with mkdocs. I close this issue. Please open an issue on the repository for the template.

**Comment by AudioLotus** [comment]
Sorry to bother again, but do you mean this repository?

https://github.com/ObsidianPublisher/mkdocs-publisher-template

There doesn't seem to be the button for me to open an issue there, so I cannot open one. Is there another method to doing so? Thanks!

**Comment by Lisandra-dev** [comment]
Have you really read the template when you open an issue here?
In the checkbox, there are a link to the github repository, where you can make an issue.

**Comment by AudioLotus** [comment]
Yes, but I do have a brain injury which makes remembering / understanding that sort of stuff quite a challenge.

Thanks.

**Comment by Lisandra-dev** [comment]
No worry, it's just, as I'm alone on the project, making little tiresome to manage everything, including the moderation and indication. 
I will love to have easily bot to help moderation with that…
Sorry if I sounded rude!

**Comment by AudioLotus** [comment]
It's cool! I can totally understand how that can be quite a burden at times. I'll go ahead and submit the issue!

Thanks so much for all you do!
