### ISSUE TITLE
[FR]: Make Dataview conversion compatible with Plugin Groups plugin

### ISSUE THREAD

**Issue by anareaty** [ObsidianPublisher/obsidian-github-publisher#305]
### Issue validation

- [X] I checked the issue to prevent duplicate
- [X] My issue concern doesn't concern the [Mkdocs template](https://github.com/ObsidianPublisher/template-main/)

### Is your feature related to a problem ?

I use the Plugin Groups plugin to delay plugins loading and make Obsidian start faster. It is especially useful with Dataview, because Dataview slows down startup a lot. Unfortunately loading Dataview via Plugins Groups instead of normal load makes the Github Publisher think that Dataview is not enabled at all. As a result my Dataview queries in published notes are not converted. If I disable Plugin Groups and enable Dataview normally, queries are converted all right.

### What solution do you want to see ?

As far as I understand the plugin checks if Dataview is enabled in Obsidian settings, and to load plugins via Plugin Groups you need to disable them in settings. May be it is possible to check if Dataview is loaded some other way, or add an option to skip checking at all?

### Describe the alternative you've considered

Alternative is to not use the Plugin Groups plugin for Dataview, which is not optimal, because it makes loading slow.

### OS

Android, Windows

### Plugin version

6.13.6

### Obsidian version & debug log

```bash session
Obsidian version 1.4.16
```

**Comment by Lisandra-dev** [comment]
Did you try to load Publisher after Dataview?

**Comment by anareaty** [comment]
Yes. It doesn't help.
I tried to make delay for Github Publisher longer, but it doesn't help either.

**Comment by Lisandra-dev** [comment]
I close the issue because:
- I can't do anything about it
- It doesn't concern the plugin directly but more the plugin group plugin ; 
- Dataview is a pretty complexe plugin, notably because it's in maintenance mode and Obsidian seems to develop another database management methods.
- The plugin group itself is in maintenance mode and have a lot of bug (and more and more to come) because it's in maintenance mode / abandonned.
