### ISSUE TITLE
[Bug]: Couldn't upload Attachments with Obsidian folder structure while using the Folder Path replacer

### ISSUE THREAD

**Issue by vu-truong** [ObsidianPublisher/obsidian-github-publisher#314]
### Issue validation

- [X] I checked the issue to prevent duplicate
- [X] I checked my configurations files and the documentation
- [X] My issue concern doesn't concern the [Mkdocs template](https://github.com/ObsidianPublisher/template-main/)

### Command used

Upload single current active note

### Plugin version

6.15.5

### Describe the bug

Hi, Lisandra
I've found that I couldn't upload Attachments with Obsidian folder structure while using the Folder Path replacer:
<img width="424" alt="image" src="https://github.com/ObsidianPublisher/obsidian-github-publisher/assets/29748838/aaf0c187-e47f-4064-ae2b-ec4a05a72d38">

If I remove the Folder Path replacer, everything is okay. So I think there is a bug about replacing the Folder Path when uploading Attachments with Obsidian folder structure.

Here is my vault:
<img width="512" alt="image" src="https://github.com/ObsidianPublisher/obsidian-github-publisher/assets/29748838/f755289d-b8d0-4389-bfad-a4faa09dde72">

Here is my attachment config:
<img width="608" alt="image" src="https://github.com/ObsidianPublisher/obsidian-github-publisher/assets/29748838/64157238-7d21-4940-b9cb-808d948d30e5">

And here is the error:
<img width="255" alt="image" src="https://github.com/ObsidianPublisher/obsidian-github-publisher/assets/29748838/f426ed47-6fc5-4ab6-a787-4e832d8c45f8">

### Minimal Reproducible Example

```markdown
---
share: true
comments: false
hidden: true
title: Home
---


![[Attachments/discord.png]]
```

### Configuration

```JSON
{
  "github": {
    "branch": "main",
    "automaticallyMergePR": true,
    "dryRun": {
      "enable": false,
      "folderName": "github-publisher"
    },
    "tokenPath": "%configDir%/plugins/%pluginID%/env",
    "api": {
      "tiersForApi": "Github Free/Pro/Team (default)",
      "hostname": ""
    },
    "workflow": {
      "commitMessage": "[PUBLISHER] Merge",
      "name": ""
    },
    "verifiedRepo": true
  },
  "upload": {
    "behavior": "obsidian",
    "defaultName": "docs",
    "rootFolder": "",
    "yamlFolderKey": "",
    "frontmatterTitle": {
      "enable": false,
      "key": "title"
    },
    "replaceTitle": [],
    "replacePath": [
      {
        "regex": "MyBlog",
        "replacement": "",
        "type": "path"
      }
    ],
    "autoclean": {
      "enable": false,
      "excluded": []
    },
    "folderNote": {
      "enable": false,
      "rename": "index.md",
      "addTitle": {
        "enable": false,
        "key": "title"
      }
    },
    "metadataExtractorPath": ""
  },
  "conversion": {
    "hardbreak": false,
    "dataview": true,
    "censorText": [],
    "tags": {
      "inline": false,
      "exclude": [],
      "fields": []
    },
    "links": {
      "internal": false,
      "unshared": false,
      "wiki": false,
      "slugify": "disable"
    }
  },
  "embed": {
    "attachments": true,
    "overrideAttachments": [],
    "keySendFile": [],
    "notes": false,
    "folder": "docs/Attachments",
    "convertEmbedToLinks": "keep",
    "charConvert": "->",
    "useObsidianFolder": true
  },
  "plugin": {
    "shareKey": "share",
    "excludedFolder": [],
    "copyLink": {
      "enable": false,
      "links": "",
      "removePart": [],
      "transform": {
        "toUri": true,
        "slugify": "lower",
        "applyRegex": []
      }
    },
    "setFrontmatterKey": "Set"
  }
}
```

### OS

Windows

### Obsidian information

```bash session
SYSTEM INFO:
	Obsidian version: v1.5.3
	Installer version: v1.4.16
	Operating system: Windows 10 Home Single Language 10.0.22621
	Login status: not logged in
	Insider build toggle: off
	Live preview: off
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Github Publisher v6.15.5

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

**Comment by Lisandra-dev** [comment]
Found what cause the 422 error :  `HttpError: path contains a malformed path component: {"resource":"Commit","field":"path","code":"invalid"}`

I forgot to normalizePath after the regex
