### ISSUE TITLE
[Bug]: <img>'s src aren't getting a base path correctly (attachmentLinks)

### ISSUE THREAD

**Issue by kurko** [ObsidianPublisher/obsidian-github-publisher#32]
### Issue validation

- [X] My issue is not a question relative to [Material Mkdocs](https://squidfunk.github.io/mkdocs-material/) nor [Mkdocs](https://www.mkdocs.org/) (*[You can open a discussion to get more help!](https://github.com/squidfunk/mkdocs-material/discussions)*)
- [X] I checked the issue to prevent duplicate
- [X] I checked my configurations files and the documentation

### Workflow

Obsidian plugin 💠

### Describe the bug

**tl;dr** with `Default Attachment Folder` (`defaultImageFolder`) set to `images/obsidian`, dev console shows that `convertLinkCitation` ignores that and returns `images/naming.png` instead of `images/obsidian/naming.png `.

It seemed to be similar to https://github.com/ObsidianPublisher/obsidian-github-publisher/issues/8, which was _supposed_ to be fixed by https://github.com/ObsidianPublisher/obsidian-github-publisher/commit/0755d375e672ceeab1a0216e0c9f4bf63ec762f7, but it wasn't.

Upon investigation, I think the culprit is [this line](https://github.com/ObsidianPublisher/obsidian-github-publisher/blob/af7de00fcf944e388c61048415e3826cb1a94ffd/plugin/contents_conversion/convertLinks.ts#L104). It was supposed to be using the default attachment path and is not. It's returning `images/naming.png`

<img width="909" alt="Screen Shot 2022-10-08 at 23 46 28" src="https://user-images.githubusercontent.com/70312/194735260-05b0fecf-9207-4173-9595-937ec12a4433.png">

You can see in the [generated PR](https://github.com/kurko/blog/commit/af227235dc48b58386f8ff5a4c9a2882b8827928#diff-03570e672ab7bc3c3a8dd5a8bea28b2a89ef57a867c0b93b7780cbbd435d9a98) that the image path is correctly `images/obsidian/naming.png`, but [the markdown file itself is not including obsidian/ in src](https://github.com/kurko/blog/commit/af227235dc48b58386f8ff5a4c9a2882b8827928#diff-50d53af29ca2bc2f6bac50c7b32562438bec64463ef984e00ecaa463c0dd6a67R11).

### How to reproduce ?

1. Set a default attachment folder (defaultImageFolder)
2. publish
3. the image tag doesn't have its path modified to include the attachment folder. It ignores it completely.

### Configuration

```
{
  "githubRepo": "blog",
  "githubName": "kurko",
  "GhToken": "ghp_[REDACTED]",
  "shareKey": "share",
  "ExcludedFolder": "",
  "fileMenu": true,
  "editorMenu": true,
  "downloadedFolder": "fixed",
  "folderDefaultName": "obsidian",
  "yamlFolderKey": "",
  "rootFolder": "",
  "workflowName": "",
  "embedImage": true,
  "defaultImageFolder": "images/obsidian",
  "autoCleanUp": true,
  "autoCleanUpExcluded": "",
  "folderNote": false,
  "convertWikiLinks": true,
  "convertForGithub": true,
  "subFolder": "",
  "embedNotes": false,
  "copyLink": false,
  "mainLink": "",
  "linkRemover": "",
  "hardBreak": false,
  "logNotice": false,
  "convertDataview": true,
  "useFrontmatterTitle": true,
  "censorText": [
    {
      "entry": "\\]\\(\\.\\/",
      "replace": "]({% link obsidian/"
    },
    {
      "entry": "\\({% link(.*)\\)",
      "replace": "({% link $1.md %})"
    }
  ],
  "inlineTags": false,
  "dataviewFields": [],
  "excludeDataviewValue": [],
  "metadataFileFields": [
    "obsidian"
  ],
  "frontmatterTitleKey": "filename",
  "shareExternalModified": false
}
```

### OS

MacOS

### Anything else?

Minor feedback: the lack of tests make it difficult to contribute

**Comment by kurko** [comment]
Found the culprit: apparently [targetList.filter((x) => !sourceList.includes(x))](https://github.com/ObsidianPublisher/obsidian-github-publisher/blob/af7de00fcf944e388c61048415e3826cb1a94ffd/plugin/contents_conversion/filePathConvertor.ts#L65) is removing the word `obsidian` from `images/obsidian/naming.png`. I don't understand why it needs to drop a directory, unsure whether it's a feature for something else or a bug.

Here's the screenshot with all values. Notice at the end, it drops the directory:

<img width="800" alt="Screen Shot 2022-10-09 at 00 07 24" src="https://user-images.githubusercontent.com/70312/194735936-f38b037f-7575-45a6-9a0b-0425d5c978d3.png">

Can you advise on how to fix this? I'm afraid it'd break other things that are expected somewhere else 😬

**Comment by Lisandra-dev** [comment]
I Will check that ! Don't worry :D

**Comment by Lisandra-dev** [comment]
I pushed a beta version of this fix, could you please try it and keep me informed about it ?

**Comment by kurko** [comment]
I can [confirm it worked](https://github.com/kurko/blog/pull/8/files#diff-50d53af29ca2bc2f6bac50c7b32562438bec64463ef984e00ecaa463c0dd6a67R11) with 4.3.7-0 (beta) 😄

**Comment by kurko** [comment]
I noticed now that links aren't working, and I think it might be due to this change (need to confirm).

Here's my config:

<img width="434" alt="Screen Shot 2022-10-09 at 19 03 06" src="https://user-images.githubusercontent.com/70312/194781703-c3595f68-80ea-4794-8d93-649c7b798ac9.png">

---

Here is the screenshot in Obsidian showing from `about` (source) to `my-digital-workbench` (target). 

<img width="861" alt="Screen Shot 2022-10-09 at 19 08 49" src="https://user-images.githubusercontent.com/70312/194781739-b758f697-0564-4b59-8643-dae62b8507c7.png">

Note that:

- the `my-digital-workbench` file has frontmatter `filename: _pages/my-digital-workbench` (with _pages), 
- the file is [deployed](https://github.com/kurko/blog/blob/cff38a5e7568f3c95fe290ecaf3017b05419c19b/obsidian/_pages/my-digital-workbench.md) to `obsidian/_pages/my-digital-workbench` as expected,
- **but** the final link in `about` [points to obsidian/my-digital-workbench](https://github.com/kurko/blog/blob/cff38a5e7568f3c95fe290ecaf3017b05419c19b/obsidian/_pages/about.md?plain=1#L28), omitting `_pages`.

**Comment by kurko** [comment]
Hm... yes it is. If you check again [this image](
![](https://user-images.githubusercontent.com/70312/194781739-b758f697-0564-4b59-8643-dae62b8507c7.png)
), the wikilink `[[my-digital-workbench|Check out my work setup]]` on the bottom right pane is a link.
