### ISSUE TITLE
[Bug]: Broken link

### ISSUE THREAD

**Issue by Blaine-Reid** [ObsidianPublisher/obsidian-github-publisher#329]
### Issue validation

- [X] I checked the issue to prevent duplicate
- [X] I checked my configurations files and the documentation
- [X] My issue concern doesn't concern the [Mkdocs template](https://github.com/ObsidianPublisher/template-main/)

### Plugin version

7.0.5

### Describe the bug

There is a broken link in the README for the `[Maintaining the project and adding new function](https://obsidian-publisher.netlify.app/developping/#general)` link and `[Help with the translation](https://obsidian-publisher.netlify.app/developing/#translation)`. `developping` has two `p`'s and just needs to be switched to one `p`

<img width="1028" alt="Screenshot 2024-04-08 at 8 21 09 AM" src="https://github.com/ObsidianPublisher/obsidian-github-publisher/assets/96265960/0380eee9-4bd3-494b-95e6-d3f1c11bfa13">

### How to reproduce ?

1. go to README
2. go to the link and click on it
3. edit the url in the browser by deleting a p and it loads the page properly

### Minimal Reproducible Example

```markdown
n/a
```

### Configuration

```JSON
n/a
```

### Obsidian information

```bash session
n/a
```

**Comment by Lisandra-dev** [comment]
Fixed in https://github.com/ObsidianPublisher/docs/commit/6efc5fd200a526487eb457e5e31b6a362accdd86
