### ISSUE TITLE
[FR]: 'Delete all before publish' option

### ISSUE THREAD

**Issue by somidad** [ObsidianPublisher/obsidian-github-publisher#333]
### Issue validation

- [X] I checked the issue to prevent duplicate
- [X] My issue concern doesn't concern the [Mkdocs template](https://github.com/ObsidianPublisher/template-main/)

### Is your feature related to a problem ?

No

## Proposal

I imagine that it would be better if there is an option 'Delete all before publish' applicable to some or all of the following:

- Upload all shared notes
- Refresh all published notes
- Refresh published and upload new notes

## Motivation

A usecase is that I renamed an already published note and publish it again, then there are two files, 'original' published file and 'renamed' published file. I want a repository to have only one file with the latest name.

## How does the proposal satisfy the motivation?

By deleting all files on the remote before publishing, the remote starts with a fresh state. Then actual publish command upload all public notes. If the pull request is merged after then, it has a rename effect virtually.

### OS

IOS, Android, MacOS, Windows, Linux

### Plugin version

7.0.2

### Obsidian version & debug log

1.5.12

I don't think debug log is required since it is not a bug report

**Comment by Lisandra-dev** [comment]
Use the autoclean function.
