### ISSUE TITLE
[FR]: Support for GitLab

### ISSUE THREAD

**Issue by OogieM** [ObsidianPublisher/obsidian-github-publisher#38]
### Issue validation

- [X] My issue is not a question relative to [Material Mkdocs](https://squidfunk.github.io/mkdocs-material/) nor [Mkdocs](https://www.mkdocs.org/) (*[You can open a discussion to get more help!](https://github.com/squidfunk/mkdocs-material/discussions)*)
- [X] I checked the issue to prevent duplicate

### Workflow

Obsidian plugin 💠

### Is your feature related to a problem ?

I am working on a large software development project with a team of volunteers. I need to share some of my Obsidian notes with them but not all my notes. The project is deeply linked in my existing personal vault. I do not want my whole vault included in the Git repository because I do not want my teammates to have access to my personal notes. All the code for both the mobile and desktop versions of the application are already on GitLab and we'd like to keep the entire ecosystem of work (python program, Android program, database queries, hardware build instructions etc.) in a single location.

### What solution do you want to see ?

Option to chose which public Git repo I want to use for syncing a single set of documents. 

### Describe the alternative you've considered

Moving everything back to GitHub.

But Git lab offers more tools that we like and are using than GitHub does. 

### OS

IOS, Android, MacOS, Windows, Linux

**Comment by Lisandra-dev** [comment]
For the moment i dont plan to set API for gitlab.
Bit feel free to do a PR
