### ISSUE TITLE
[Bug]: Image links are broken because of appended .md

### ISSUE THREAD

**Issue by sean808080** [ObsidianPublisher/obsidian-github-publisher#39]
### Issue validation

- [X] My issue is not a question relative to [Material Mkdocs](https://squidfunk.github.io/mkdocs-material/) nor [Mkdocs](https://www.mkdocs.org/) (*[You can open a discussion to get more help!](https://github.com/squidfunk/mkdocs-material/discussions)*)
- [X] I checked the issue to prevent duplicate
- [X] I checked my configurations files and the documentation

### Workflow

Obsidian plugin 💠

### Describe the bug

Images are broken when published because the image URL has .md appended to the end.

Example:
After publishing to GitHub from Obsidian, a note has the following reference too an image file:
`![Paper.Journal.1.jpeg](../images/obsidian/Paper.Journal.1.jpeg.md)`

This results in a broken image icon instead of the actual image.
Changing it to:
`![Paper.Journal.1.jpeg](../images/obsidian/Paper.Journal.1.jpeg)`

fixes the issue and the image shows as expected.

### Configuration

{
  "githubRepo": "blog",
  "githubName": "me",
  "GhToken": "token",
  "githubBranch": "main",
  "shareKey": "share",
  "shareKey": "share",
  "ExcludedFolder": "",
  "fileMenu": true,
  "editorMenu": true,
  "downloadedFolder": "fixed",
  "folderDefaultName": "obsidian",
  "yamlFolderKey": "category",
  "rootFolder": "docs",
  "workflowName": "",
  "embedImage": true,
  "defaultImageFolder": "images/obsidian",
  "autoCleanUp": true,
  "autoCleanUpExcluded": "docs/assets/js, docs/assets/meta, docs/assets/css, tags.md",
  "folderNote": true,
  "convertWikiLinks": true,
  "convertForGithub": true,
  "subFolder": "",
  "embedNotes": false,
  "copyLink": false,
  "mainLink": "",
  "linkRemover": "",
  "hardBreak": false,
  "logNotice": true,
  "convertDataview": false,
  "useFrontmatterTitle": false,
  "censorText": [
    {
      "entry": "(?<!\\\\`)\\\\[(.*?)\\\\]\\\\((?!(http|\\\\/*image|obsidian\\\\/image))(\\\\.\\\\/)*(.+?)(\\\\.md)*\\\\) ",
      "replace": "[$1]({% link obsidian/$4.md %})",
      "after": false
    },
    {
      "entry": "(?<!\\\\`)\\\\[(.*?)\\\\]\\\\(((obsidian\\\\/)?image)(.+)\\\\)",
      "replace": "[$1](/image$4)",
      "after": false
    }
  ],
  "inlineTags": false,
  "dataviewFields": [],
  "excludeDataviewValue": [],
  "metadataFileFields": [],
  "frontmatterTitleKey": "title",
  "shareExternalModified": false
}

**Comment by Lisandra-dev** [comment]
Image with `.` are not accepted in any OS (at last windows ?).

**Comment by sean808080** [comment]
I'm on a Mac.  I updated the image file name to remove extra periods and see the same issue.

`![PaperJournal1.jpeg](../images/obsidian/PaperJournal1.jpeg.md)`

A link to the actual .jpg is [here](https://imgur.com/a/HNzfxdK)

The same problem is observed with .jpg files as well.

**Comment by Lisandra-dev** [comment]
Strange. Do you have a obsidian md file example ? I didn't have this on my side, so I don't understand :w

**Comment by Lisandra-dev** [comment]
EDIT: I successfull repro the problem without regex.
Why ? Dunno. Will investigate. Thanks!

**Comment by sean808080** [comment]
Can we keep the issue open so I can be notified when it's fixed to retest.  Thanks!

**Comment by Lisandra-dev** [comment]
It's literally fixed in the last release

**Comment by sean808080** [comment]
oops..didn't realize it.  I just tested it and it's working. Thanks so much!
