### ISSUE TITLE
[Bug]: Plugin sharing files on its own without my input

### ISSUE THREAD

**Issue by QuickFastly** [ObsidianPublisher/obsidian-github-publisher#40]
### Issue validation

- [X] My issue is not a question relative to [Material Mkdocs](https://squidfunk.github.io/mkdocs-material/) nor [Mkdocs](https://www.mkdocs.org/) (*[You can open a discussion to get more help!](https://github.com/squidfunk/mkdocs-material/discussions)*)
- [X] I checked the issue to prevent duplicate
- [X] I checked my configurations files and the documentation

### Workflow

Obsidian plugin 💠

### Describe the bug

I was working on merging a few notes into one main note by opening the other notes in a new window, then copying and pasting from the new window to the main window. Every time I pasted something with that extra window open, the plugin uploaded the note.

I also needed to insert some templates with ctrl+T into my main note while doing this, and every time I did that, the plugin uploaded the note. This only happened with the new window open. I have no hotkeys set for this plugin to cause conflicts.

It also uploaded the note a few times just by typing a header into the main Obsidian window, but that happened with less than half of the headers I typed in, and again, only with the new window open.

I'm using version 4.5.1 of the plugin, and version 1.0.3 of Obsidian.

### How to reproduce ?

1. Open a note in a new window
2. Copy and paste text from the new window into another note in the main Obsidian window
3. Try inserting a template into a note in the main Obsidian window
4. See what happens

### Configuration

There is no configuration setting to allow this to happen, and I have no hotkeys set. My configuration is default.

### OS

Linux (EndeavourOS)

**Comment by Lisandra-dev** [comment]
The only option that can create this behavior is that : 
![image](https://user-images.githubusercontent.com/30244939/202490407-348db0bd-c5e0-441d-93fc-4f7bf32208fc.png)

**Comment by QuickFastly** [comment]
Testing with that option both on and off yields the same result.

**Comment by Lisandra-dev** [comment]
I can't repro this behavior with my testing repo.
Maybe you have a hotkey set somewhere.

**Comment by QuickFastly** [comment]
I have set ctrl+T to insert template, and I have no hotkeys set as ctrl+V, or shift+3, and I can't think of any other potential key combinations to cause this. I have no hotkeys set for this plugin at all, though it is kind of interesting that most options show "blank" but the share active file hotkey is _literally_ blank.
![image](https://user-images.githubusercontent.com/96478803/202495308-a46bd063-f95f-45d6-874d-84d2bc0751de.png)

**Comment by Lisandra-dev** [comment]
Have you something in the console?
Could you try using the plugin in a blank vault / disabling all other plugin ? 

As I said, on my windows 11 with my own configuration, I don't have this behavior ! 

Another idea is around a problem from the Obsidian API with specially Linux... I don't have Linux on my computer ASAP but I can create a VM to try it.

**Comment by Lisandra-dev** [comment]
You can transfer the configuration with copying the `data.json` but, if you disable all plugin... I don't know, to be honest… 
For me it's an error with the API for linux ? As I don't have this bug on Windows...

**Comment by runarsf** [comment]
This is happening to me on Linux (EndeavourOS) as well.
I can't find any relevant information in the console, and I don't have any hotkeys assigned.

So far it has only happened when leaving the published note by clicking on a linked note that wasn't created yet, but this might be unrelated.

**Comment by Lisandra-dev** [comment]
Do you have the auto-publishing option enabled, by chance ? 
I dunno why it happens on linux :/

**Comment by runarsf** [comment]
I'm not sure which option you're referring to, is it in the plugins settings panel?
I have the "auto clean up" and "automatically merge pull requests" options enabled.

**Comment by Lisandra-dev** [comment]
It's in the settings, plugin tab. 

![image](https://user-images.githubusercontent.com/30244939/223137436-893bf4c4-582f-46a8-84a1-f0cefd430ca1.png)

Sorry I use the wrong name here :'D

**Comment by runarsf** [comment]
No problem, I do have that option enabled yes, I'll try disabling it and see if it keeps happening - thanks!

**Comment by runarsf** [comment]
It's unfortunately still happening, and it usually creates a pull request with conflicts in my repository.
It seems to be connected to switching to/from a published files somehow.

**Comment by runarsf** [comment]
It seems like it might be caused by external modifications to the file after all, even if the setting is disabled.

I'm using a plugin called "Update time on edit", which updates the frontmatter when you switch to a different file. Disabling this plugin seems to stop this from happening.

**Comment by Lisandra-dev** [comment]
Thanks!

**Comment by Lisandra-dev** [comment]
I removed the option in .3 in hope to remove this bug.
Please inform me if the bug continue to occurs. It doesn't happens on my side (Windows + Update time on edit plugin)

**Comment by QuickFastly** [comment]
I just updated the plugin and tested this, and it didn't happen again.
