### ISSUE TITLE
[Bug]: Status bar has duplicated entries after error

### ISSUE THREAD

**Issue by tobiasvl** [ObsidianPublisher/obsidian-github-publisher#45]
### Issue validation

- [X] My issue is not a question relative to [Material Mkdocs](https://squidfunk.github.io/mkdocs-material/) nor [Mkdocs](https://www.mkdocs.org/) (*[You can open a discussion to get more help!](https://github.com/squidfunk/mkdocs-material/discussions)*)
- [X] I checked the issue to prevent duplicate
- [X] I checked my configurations files and the documentation

### Workflow

Obsidian plugin 💠

### Describe the bug

My Obsidian status bar has multiple entries from this plugin.

There's also an error occurring with the plugin, but I'm not sure if that's related.

### How to reproduce ?

Unsure.

### Configuration
```
{
  "githubRepo": "blog-test",
  "githubName": "tobiasvl",
  "GhToken": "RETRACTED",
  "githubBranch": "master",
  "shareKey": "published",
  "ExcludedFolder": "",
  "fileMenu": false,
  "editorMenu": false,
  "downloadedFolder": "fixed",
  "folderDefaultName": "_posts",
  "yamlFolderKey": "",
  "rootFolder": "",
  "workflowName": "",
  "embedImage": true,
  "defaultImageFolder": "assets/images",
  "autoCleanUp": false,
  "autoCleanUpExcluded": "",
  "folderNote": false,
  "convertWikiLinks": true,
  "convertForGithub": false,
  "subFolder": "",
  "embedNotes": false,
  "copyLink": false,
  "mainLink": "",
  "linkRemover": "",
  "hardBreak": false,
  "logNotice": true,
  "convertDataview": true,
  "useFrontmatterTitle": false,
  "censorText": [],
  "inlineTags": false,
  "dataviewFields": [
    "jekyll-tags"
  ],
  "excludeDataviewValue": [],
  "metadataFileFields": [],
  "frontmatterTitleKey": "title",
  "shareExternalModified": false
}
```
### Relevant log output

```shell
TypeError: Cannot read properties of undefined (reading 'commit')
    at GithubBranch.eval (plugin:obsidian-mkdocs-publisher:2625:40)
    at Generator.next (<anonymous>)
    at fulfilled (plugin:obsidian-mkdocs-publisher:47:24)
```

### Anything else?

![image](https://user-images.githubusercontent.com/80824/204106543-37cc8ef2-73fe-4f85-bd0d-d1545060cfc9.png)

**Comment by Lisandra-dev** [comment]
EDIT and remove your github token !!!

**Comment by tobiasvl** [comment]
Haha, thank you. Good looking out, I totally missed that, but the token was actually an old revoked one.

**Comment by tobiasvl** [comment]
Seems to be a duplicate of #6

**Comment by tobiasvl** [comment]
Still happening:

![image](https://user-images.githubusercontent.com/80824/204113726-e827bdc7-17c2-484f-acbb-e342d0aaf3a5.png)

**Comment by Lisandra-dev** [comment]
I must try to understand how I can remove it before the end of the timer...
