### ISSUE TITLE
[Bug]: plugin fail to launch if language not found in the translation

### ISSUE THREAD

**Issue by Valkann** [ObsidianPublisher/obsidian-github-publisher#53]
### Issue validation

- [X] My issue is not a question relative to [Material Mkdocs](https://squidfunk.github.io/mkdocs-material/) nor [Mkdocs](https://www.mkdocs.org/) (*[You can open a discussion to get more help!](https://github.com/squidfunk/mkdocs-material/discussions)*)
- [X] I checked the issue to prevent duplicate
- [X] I checked my configurations files and the documentation

### Workflow

Obsidian plugin 💠

### Describe the bug

Since the update the plugin is impossible to activate

![image](https://user-images.githubusercontent.com/11332736/205125071-24f5629b-f81c-4819-b6e7-5967f3c2c652.png)

### Configuration

***MODERATED BECAUSE GITHUB TOKEN**

### OS

Windows

**Comment by Lisandra-dev** [comment]
Yeah, It seems there was a problem during the build with github actions!

**Comment by Valkann** [comment]
HI,

Mys obsdian version 

![image](https://user-images.githubusercontent.com/11332736/205224413-54c302d7-9337-497c-90b4-d2e37afc7e41.png)

I have this error in the console

![image](https://user-images.githubusercontent.com/11332736/205224529-0055dff0-0a8c-496d-92ec-47fa815bb35b.png)

I will try to manually update

**Comment by Valkann** [comment]
I tried manually but it didn't change the error

[data.json.txt](https://github.com/ObsidianPublisher/obsidian-github-publisher/files/10138520/data.json.txt)

Here the data json without the token :)

**Comment by Lisandra-dev** [comment]
Okay, I'm stupid. Thanks for the log !

**Comment by Valkann** [comment]
It's work :) Thanks a lot.
