### ISSUE TITLE
[Bug]: Files no longer have the .md extension

### ISSUE THREAD

**Issue by Valkann** [ObsidianPublisher/obsidian-github-publisher#64]
### Issue validation

- [X] My issue is not a question relative to [Material Mkdocs](https://squidfunk.github.io/mkdocs-material/) nor [Mkdocs](https://www.mkdocs.org/) (*[You can open a discussion to get more help!](https://github.com/squidfunk/mkdocs-material/discussions)*)
- [X] I checked the issue to prevent duplicate
- [X] I checked my configurations files and the documentation

### Workflow

Obsidian plugin 💠

### Describe the bug

Files sent by Github publisher do not keep the .md extension once they arrive on Github.

example : https://github.com/Valkann/Obsidian/tree/main/docs/week

![image](https://user-images.githubusercontent.com/11332736/210565707-33c7a25a-105e-4a2a-b0ec-7ff34ad1b983.png)

### How to reproduce ?

Go to : https://github.com/Valkann/Obsidian/tree/main/docs/week

### Configuration

{
  "githubRepo": "Obsidian",
  "githubName": "Valkann",
  "GhToken": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "githubBranch": "main",
  "shareKey": "share",
  "excludedFolder": [],
  "fileMenu": true,
  "editorMenu": true,
  "downloadedFolder": "yaml",
  "folderDefaultName": "docs/notes",
  "yamlFolderKey": "category",
  "rootFolder": "docs",
  "workflowName": "",
  "embedImage": true,
  "defaultImageFolder": "",
  "autoCleanUp": true,
  "autoCleanUpExcluded": [],
  "folderNote": false,
  "folderNoteRename": "index.md",
  "convertWikiLinks": true,
  "convertForGithub": true,
  "subFolder": "",
  "embedNotes": true,
  "copyLink": false,
  "mainLink": "",
  "linkRemover": "",
  "hardBreak": false,
  "logNotice": false,
  "convertDataview": true,
  "useFrontmatterTitle": false,
  "censorText": [],
  "inlineTags": false,
  "dataviewFields": [],
  "excludeDataviewValue": [],
  "metadataFileFields": [],
  "frontmatterTitleKey": "title",
  "shareExternalModified": true,
  "automaticallyMergePR": true,
  "metadataExtractorPath": "",
  "convertInternalNonShared": false,
  "frontmatterTitleRegex": "",
  "frontmatterTitleReplacement": "",
  "ExcludedFolder": []
}

### OS

Windows

**Comment by Lisandra-dev** [comment]
Yup, fixed in 4.10.2 normally. Did you check your version ? I pushed the 4.11.0 btw, and normally it is fixed in this release for sure

**Comment by Valkann** [comment]
It seems to work with the update but I have duplicates.
At worst, I remove them by hand

![image](https://user-images.githubusercontent.com/11332736/210616223-1dbc0796-8882-46fd-91d7-a575318590a3.png)

**Comment by Lisandra-dev** [comment]
Yeah, sorry for that. 
In my case, when I noticed that, I removed the file using : 
- Search the PR where everything explode
- Revert it, if possible.
- If it's not possible, you need to open a codespace or the repo in local and : 
- Create a new branch based on your git history (so take the commit before everything explode), named like `revert`
- `git checkout main`
- `git checkout revert docs/.`

It will resolve the problem.

Sorry for that. I noticed the error to much late ;;

**Comment by Valkann** [comment]
Don't worry about that just some advance search in the windows explorer and a commit and it's good 👍
