### ISSUE TITLE
[FR]: Add a page in documentation website to explain the behavior of each command

### ISSUE THREAD

**Issue by Lisandra-dev** [ObsidianPublisher/obsidian-github-publisher#77]
### Discussed in https://github.com/ObsidianPublisher/obsidian-github-publisher/discussions/75

<div type='discussions-op-text'>

<sup>Originally posted by **andrey-jef** January 13, 2023</sup>
Hi,

Since I have some ambiguity when experimenting the plugin's command, I would like to suggest a dedicated page in [documentation website](https://obsidian-publisher.netlify.app/) to explain the behavior of each command in the plugin [Github Publisher](https://github.com/ObsidianPublisher/obsidian-github-publisher).

Here is my attempt to clarify the behavior of each command, for your consideration.

`Github Publisher: Share active file` -> should change to `Github Publisher: Upload single current active note`
- Behavior: publish only the single current active note, this command also add the key `share: true` into the frontmatter of the current active note

`Github Publisher: Upload all shared notes` -> change to `Github Publisher: Upload multiple notes`
- Behavior: publish all notes which have the key `share: true` in their frontmatter

`Github Publisher: Upload new shared notes` -> change to `Github Publisher: Upload unpublished notes`
- Behavior: publish only the notes satisfying these two conditions: have the key `share: true` in their frontmatter AND were not published since last upload

`Github Publisher: Check validity of this repository`
- Behavior: check and display the result whether there is a valid connection between the plugin and its attached repository

`Github Publisher: Upload all edited notes since last upload` -> change to `Github Publisher: Refresh content of all published notes`
- Behavior: publish only the notes satisfying these two conditions: have the key `share: true` in their frontmatter AND were recently modified since last upload

`Github Publisher: Upload all new and edited notes since last upload`
- This command is the combination of 2 command `Github Publisher: Upload new shared notes`  and `Github Publisher: Upload all edited notes since last upload`, isn't it? In this case, is it better to remove this command in cause of its ambiguity?
- Behavior: publish only the notes satisfying these two conditions: have the key `share: true` in their frontmatter AND (were newly created OR recently modified since last upload)</div>

**Comment by andrey-jef** [comment]
Just have more experience with the commands of plugin `Github Publisher`. Based on my daily usage where I just write notes in Obsidian, then open `Command Palette` to sync all changes to repo. In order to further reduce the ambiguity, what do you think if the plugin would have only 3 commands, as follows?

1. `Github Publisher: Publish single currently active note`
    - Behavior: publish all notes which have the key share: true in their frontmatter
2. `Github Publisher: Sync published notes to remote repository`
    - Behavior: publish all notes which have the key `share: true` in their frontmatter AND (were not published since last upload OR were recently modified since last upload OR were newly created)
    - This command is expected to replace all these commands below:
        - `Github Publisher: Upload all shared notes`
        - `Github Publisher: Upload all edited notes since last upload`
        - `Github Publisher: Upload all new and edited notes since last upload`
3. `Github Publisher: Check validity of this repository`
    - Behavior: check and display the result whether there is a valid connection between the plugin and its attached repository

**Comment by Lisandra-dev** [comment]
To be honest, I'm not a fan. I think there is some moment where you need one of the three.

**Comment by Lisandra-dev** [comment]
So, I renamed : 
- Share active file ->Upload single current active note
- Upload all shared notes ->Upload multiple notes
- Upload new shared notes -> Upload unpublished notes
- Upload all edited notes since last upload -> Refresh published notes
- Upload all new and edited notes since last upload →  Refresh published and upload new notes
- Remove unshared and deleted file in repository → Purge unshared and deleted files 
- Check validity of this repository →  Test the connection to the configured repository

So there are : 
- 3 `Upload` commands
- 2 `Refresh` commands
- 1 purge
- 1 testing

**Comment by andrey-jef** [comment]
> So, I renamed :
> 
> * Share active file ->Upload single current active note
> * Upload all shared notes ->Upload multiple notes
> * Upload new shared notes -> Upload unpublished notes
> * Upload all edited notes since last upload -> Refresh published notes
> * Upload all new and edited notes since last upload →  Refresh published and upload new notes
> * Remove unshared and deleted file in repository → Purge unshared and deleted files
> * Check validity of this repository →  Test the connection to the configured repository
> 
> So there are :
> 
> * 3 `Upload` commands
> * 2 `Refresh` commands
> * 1 purge
> * 1 testing

Awesome. It sounds neat and concise.

But what is the difference between `unshared` in the `Purge unshared and deleted files` and `unpublished` in the `Upload unpublished notes` command?

**Comment by Lisandra-dev** [comment]
Oh, it's a typo ! Thanks :)

**Comment by Lisandra-dev** [comment]
Hello, the file is here : https://github.com/ObsidianPublisher/obsidian-github-publisher/blob/master/docs/en/COMMANDS.md

**Comment by andrey-jef** [comment]
> Hello, the file is here : https://github.com/ObsidianPublisher/obsidian-github-publisher/blob/master/docs/en/COMMANDS.md

Thanks for updating the docs.

I'm curious to learn why do you have to maintain the documentation for `Github Publisher` plugin in two separate repo? What's the reason for the difference between [`docs` folder inside plugin repo](https://github.com/ObsidianPublisher/obsidian-github-publisher/tree/master/docs) and [obsidian-mkdocs-publisher-docs](https://github.com/ObsidianPublisher/obsidian-mkdocs-publisher-docs)?

**Comment by Lisandra-dev** [comment]
Because : 
- I love complicated things (no, it's a joke!)
- There is too much files
- Mkdocs doesn't like monorepo 


There is no difference between the file in docs/ and the docs repository. In fact, the docs repository is sync with the plugin repo, so when I do a push, the file are sync. It's pretty convenient, and it's is used to sync update for the two template for example. 

The docs repo is published on netlify, but for the moment, there are a bug on mkdocs building. But the files are present and can be read on github. 

I also put the file in the docs/ folder in Publisher because sometimes, people doesn't go directly on the big documentation and check first the docs in the plugin directly.

**Comment by clutterwhy** [comment]
> Hello, the file is here : https://github.com/ObsidianPublisher/obsidian-github-publisher/blob/master/docs/en/COMMANDS.md

This link is 404 error now.
