### ISSUE TITLE
[Bug]: Repo not found but repo exist

### ISSUE THREAD

**Issue by Lisandra-dev** [ObsidianPublisher/obsidian-github-publisher#80]
### Issue validation

- [X] My issue is not a question relative to [Material Mkdocs](https://squidfunk.github.io/mkdocs-material/) nor [Mkdocs](https://www.mkdocs.org/) (*[You can open a discussion to get more help!](https://github.com/squidfunk/mkdocs-material/discussions)*)
- [X] I checked the issue to prevent duplicate
- [X] I checked my configurations files and the documentation

### Workflow

Obsidian plugin 💠

### Describe the bug

When the plugin is firstly installed or the settings are emptied (and after filled) the plugin didn't found the repository. Reloading the plugin manually and try the repo allow to the plugin to connect to github.

### How to reproduce ?

1. Empty the settings, with deleting the `data.json` file or throught the Obsidian Settings
2. Reload the plugin
3. Fill the settings
4. Try to connect to github ; Give me error 
5. Reloading the plugin
6. Try to connect : no problem

### Configuration

Default settings + any valid repo with valid token

### Relevant log output

```shell
/
```

### OS

IOS, Windows

# How to fix 

For the moment, the only way to fix the plugin is to forcing reloading it throught Obsidian. Warning, it's not reload Obsidian (it didn't change any thing), just the plugin, throught the community plugin panel (activate/desactivate). After that, everything will work as intended.

**Comment by Lisandra-dev** [comment]
> **Warning**  
> For the moment, the only way to get ride this bug is to reload the plugin through obsidian.

**Comment by ArneNostitz** [comment]
i had the same issue - only way to solve it for me was to make the repo public... is this how its intended? would like to keep my files private though ;)

**Comment by Lisandra-dev** [comment]
Nan, I tryed with any repo, public and private and the issue appear IN ALL METHODS.
The only way to repear this bug is to reload the plugin throught obsidian. Not reloading obsidian, just the plugin.

**Comment by ArneNostitz** [comment]
force reload did fix it for a private repo. thanks

**Comment by Lisandra-dev** [comment]
Normally closed in 4.11.14
