### ISSUE TITLE
[Bug]: Error during publish

### ISSUE THREAD

**Issue by Valkann** [ObsidianPublisher/obsidian-github-publisher#97]
### Issue validation

- [X] My issue is not a question relative to [Material Mkdocs](https://squidfunk.github.io/mkdocs-material/) nor [Mkdocs](https://www.mkdocs.org/) (*[You can open a discussion to get more help!](https://github.com/squidfunk/mkdocs-material/discussions)*)
- [X] I checked the issue to prevent duplicate
- [X] I checked my configurations files and the documentation

### Workflow

Obsidian plugin 💠

### Describe the bug

when I run a publish I get this error in the Obsidian console.

```
plugin:obsidian-mkdocs-publisher:32 Uncaught (in promise) TypeError: t.endsWith is not a function
    at Uu (plugin:obsidian-mkdocs-publisher:32:2995)
    at Hu (plugin:obsidian-mkdocs-publisher:32:3328)
    at Re (plugin:obsidian-mkdocs-publisher:32:4204)
    at Vt.getAllFileWithPath (plugin:obsidian-mkdocs-publisher:36:6728)
    at eval (plugin:obsidian-mkdocs-publisher:33:12439)
    at Generator.next (<anonymous>)
    at eval (plugin:obsidian-mkdocs-publisher:6:1359)
    at new Promise (<anonymous>)
    at D (plugin:obsidian-mkdocs-publisher:6:1179)
    at Qa (plugin:obsidian-mkdocs-publisher:33:12357)
```

### Configuration

{
  "githubRepo": "Obsidian",
  "githubName": "Valkann",
  "GhToken": "XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "githubBranch": "main",
  "shareKey": "share",
  "excludedFolder": [],
  "fileMenu": true,
  "editorMenu": true,
  "downloadedFolder": "yaml",
  "folderDefaultName": "docs/notes",
  "yamlFolderKey": "category",
  "rootFolder": "docs",
  "workflowName": "",
  "embedImage": true,
  "defaultImageFolder": "",
  "autoCleanUp": true,
  "autoCleanUpExcluded": [],
  "folderNote": false,
  "folderNoteRename": "index.md",
  "convertWikiLinks": true,
  "convertForGithub": true,
  "subFolder": "",
  "embedNotes": true,
  "copyLink": false,
  "mainLink": "",
  "linkRemover": "",
  "hardBreak": false,
  "logNotice": false,
  "convertDataview": true,
  "useFrontmatterTitle": false,
  "censorText": [],
  "inlineTags": false,
  "dataviewFields": [],
  "excludeDataviewValue": [],
  "metadataFileFields": [],
  "frontmatterTitleKey": "title",
  "shareExternalModified": true,
  "automaticallyMergePR": true,
  "metadataExtractorPath": "",
  "convertInternalNonShared": false,
  "frontmatterTitleRegex": "",
  "frontmatterTitleReplacement": "",
  "ExcludedFolder": []
}

### OS

Windows

**Comment by Lisandra-dev** [comment]
- Plugin version 
- Commands tryed?

**Comment by Valkann** [comment]
Version 4.11.16
Command : refresh published and upload new notes

**Comment by Valkann** [comment]
Hum my bad 

The problem was on my side, I mismanaged a category. 

This notation returns the error I had earlier.

```YAML
category: 
- projets/MOTW/MDF/monstre
```

I close the subject, sorry again

**Comment by Lisandra-dev** [comment]
Good to know anyway ! Maybe I can create a way to handle this (or prevent errors)
