### ISSUE TITLE
[FR]: Allow support for Github Enterprise

### ISSUE THREAD

**Issue by vswraith** [ObsidianPublisher/obsidian-github-publisher#98]
### Issue validation

- [X] My issue is not a question relative to [Material Mkdocs](https://squidfunk.github.io/mkdocs-material/) nor [Mkdocs](https://www.mkdocs.org/) (*[You can open a discussion to get more help!](https://github.com/squidfunk/mkdocs-material/discussions)*)
- [X] I checked the issue to prevent duplicate

### Workflow

Obsidian plugin 💠

### Is your feature related to a problem ?

We need an option to allow publishing to GitHub Enterprise repos

### What solution do you want to see ?

Allow user to enter Github enterprise  repo url.

### OS

MacOS, Linux

**Comment by vswraith** [comment]
Its effectively github but hosted on an internal server(https://github.com/enterprise). So basically if we have an option in the plugin to give the full url of the repo,it should be enough as right now there is no way to give the git repo url

**Comment by Lisandra-dev** [comment]
Okay, I think I can do something, but I need confirmation!
https://docs.github.com/en/enterprise-server@3.7/rest/guides/scripting-with-the-rest-api-and-javascript
Normally, I just need to changes this https://github.com/ObsidianPublisher/obsidian-github-publisher/blob/504418dde38cfa6e7d1c1ec82d423dfa72303229/plugin/main.ts#L41
with adding an baseURL things : 
```
import { Octokit } from "octokit";

const octokit = new Octokit({ 
  baseUrl: "http(s)://HOSTNAME/api/v3",
  auth: 'YOUR-TOKEN',
});
```
Is the HOSTNAME the same as your GitHub repo name, or it's other things? 

At last, it doesn't seem difficult at all to introduce this!

Just a question: Do you use Obsidian for works ? Do you have an Obsidian License if so ?

**Comment by Lisandra-dev** [comment]
Hey!
Could you please try the new beta : 4.12.0-5 ?

**Comment by vswraith** [comment]
Thanks, will give it a try.
I have bought the license so can use it for work as Confluence is too painful to use :)
